In [1]:
outside = ["G1", "G1", "G1", "G2", "G2", "G2"]
inside = [1, 2, 3, 1, 2, 3]
hier_index = list(zip(outside, inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [3]:
import pandas as pd

In [4]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [5]:
outside = ["A", "A", "A", "B", "B", "B"]
inside = [1, 2, 3, 1, 2, 3]
hier_index = list(zip(outside, inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex(levels=[['A', 'B'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [7]:
import numpy as np

pd.DataFrame(np.random.rand(6, 2), index=hier_index, columns=["A", "B"])

A         B
A 1  0.860792  0.064948
  2  0.975604  0.381659
  3  0.360710  0.697070
B 1  0.696117  0.697751
  2  0.856253  0.185117
  3  0.563646  0.826245

In [8]:
hier_index = list(zip(["A", "A", "A", "B", "B", "B"], [1, 2, 3, 1, 2, 3]))
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex(levels=[['A', 'B'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [11]:
df = pd.DataFrame(np.random.rand(6, 2), index=hier_index, columns=["X", "Y"])

In [12]:
df

X         Y
A 1  0.133253  0.972275
  2  0.998355  0.223726
  3  0.105610  0.717106
B 1  0.294661  0.645476
  2  0.806107  0.511982
  3  0.081566  0.253723

In [14]:
df.loc["A"].loc[1]

X    0.133253
Y    0.972275
Name: 1, dtype: float64

In [16]:
df.index.names

FrozenList([None, None])

In [17]:
df.index.names = ["Group", "No."]

In [18]:
df

X         Y
Group No.                    
A     1    0.133253  0.972275
      2    0.998355  0.223726
      3    0.105610  0.717106
B     1    0.294661  0.645476
      2    0.806107  0.511982
      3    0.081566  0.253723

In [20]:
df.loc["B"].loc[2]['Y']

0.51198229355167624

In [26]:
df2 = pd.DataFrame([[1, 2, np.nan], [3, np.nan, 5]], columns=["A", "B", "C"])
df2

A    B    C
0  1  2.0  NaN
1  3  NaN  5.0

In [25]:
df3 = pd.DataFrame({"A": [1, 2, np.nan],
                    "B": [5, np.nan, np.nan],
                    "C": [1, 2, 3]})

df3

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [29]:
len(np.arange(10))

10

In [34]:
a = np.arange(0, 6) + np.arange(0, 51, 10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [35]:
a[3:, [0, 2, 5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [36]:
!cat pwd

cat: pwd: No such file or directory


In [48]:
np.random.shuffle(a)
a.sort(axis=0)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [51]:
np.may_share_memory(a, a[[2, 3]])

False

In [54]:
np.insert(np.diag([2, 3, 4, 5, 6]), 0, 0, 0)

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [55]:
np.zeros((2, 2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [57]:
help(np.zeros)

Help on built-in function zeros in module numpy.core.multiarray:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    ones_like : Return an array of ones with shape and type of input.
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting v

In [58]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [59]:
np.allclose(a, a)

True

In [60]:
np.array_equal(a, a)

True

In [63]:
np.may_share_memory(a, a.flatten())

False

In [65]:
a.mean(axis=1)

array([  2.5,  12.5,  22.5,  32.5,  42.5,  52.5])

In [72]:
b = np.array([[3, 7, 2], [8, 1, 3]])
b

array([[3, 7, 2],
       [8, 1, 3]])

In [70]:
b.sort(axis=0)
b

array([[1, 3, 7],
       [2, 3, 8]])

In [71]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [76]:
np.sort(b.ravel()).reshape((2, 3))

array([[1, 2, 3],
       [3, 7, 8]])

In [77]:
a[0, 3:5]

array([3, 4])

In [78]:
np.array([1, 0, 1], dtype=bool)

array([ True, False,  True], dtype=bool)

In [79]:
np.median(a, axis=1)

array([  2.5,  12.5,  22.5,  32.5,  42.5,  52.5])

In [80]:
np.sort(b, axis=1)

array([[2, 3, 7],
       [1, 3, 8]])

In [91]:
c = np.array([4, 3, 1, 2])


In [93]:
cc = np.argsort(c)
cc

array([2, 3, 1, 0])

In [94]:
c

array([4, 3, 1, 2])

In [95]:
c[cc]

array([1, 2, 3, 4])

In [96]:
np.random.shuffle(c)

In [97]:
c

array([1, 3, 4, 2])

In [98]:
np.zeros((2, 2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [99]:
c

array([1, 3, 4, 2])

In [100]:
c.sort()

In [101]:
c

array([1, 2, 3, 4])

In [102]:
np.allclose(a, a)

True

In [103]:
np.array_equal(a, a)

True

In [104]:
np.sort(a, axis=1)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [117]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [118]:
a.sum()

45

In [119]:
a.sum(axis=1) # sum rows!

array([ 6, 15, 24])

In [120]:
a.sum(axis=0) # sum columns!

array([12, 15, 18])

In [113]:
df = pd.DataFrame(data=a)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [116]:
df.sum(axis=1) # sum rows!c = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))

0     6
1    15
2    24
dtype: int64

In [121]:
df.sum(axis=0) # sum columns!

0    12
1    15
2    18
dtype: int64

In [123]:
c = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
c

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [124]:
c[2]

array([35, 40, 45])

In [125]:
np.random.randn(2, 2)

array([[ 0.56406308, -0.25750935],
       [-1.8167599 ,  1.60081146]])

In [126]:
np.arange(0, 50).reshape((5, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [127]:
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [128]:
np.linspace(0.01, 1, 100)

array([ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,
        0.1 ,  0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,
        0.19,  0.2 ,  0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,
        0.28,  0.29,  0.3 ,  0.31,  0.32,  0.33,  0.34,  0.35,  0.36,
        0.37,  0.38,  0.39,  0.4 ,  0.41,  0.42,  0.43,  0.44,  0.45,
        0.46,  0.47,  0.48,  0.49,  0.5 ,  0.51,  0.52,  0.53,  0.54,
        0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ,  0.61,  0.62,  0.63,
        0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ,  0.71,  0.72,
        0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ,  0.81,
        0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ,
        0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ])

In [135]:
np.arange(0.01, 1.01, 0.01).reshape((10, 10))

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [30]:
import numpy as np
a = np.array([[1, 55, 44], [99, 0, 2], [2, 11, 10]])
a

array([[ 1, 55, 44],
       [99,  0,  2],
       [ 2, 11, 10]])

In [34]:
np.sort(a, axis=0)

array([[ 1,  0,  2],
       [ 2, 11, 10],
       [99, 55, 44]])

In [38]:
2**np.arange(0, 5)

array([ 1,  2,  4,  8, 16])

In [39]:
a

array([[ 1, 55, 44],
       [99,  0,  2],
       [ 2, 11, 10]])

In [41]:
np.median(a, axis=0)

array([  2.,  11.,  10.])

In [42]:
y = np.array([[1, 2, 3], [5, 6, 1]])

In [43]:
y

array([[1, 2, 3],
       [5, 6, 1]])

In [44]:
a

array([[ 1, 55, 44],
       [99,  0,  2],
       [ 2, 11, 10]])

In [47]:
a.sum(axis=1)

array([100, 101,  23])

In [49]:
np.sort(a, axis=1)

array([[ 1, 44, 55],
       [ 0,  2, 99],
       [ 2, 10, 11]])

In [51]:
np.median(a, axis=1)

array([ 44.,   2.,  10.])

In [52]:
a.sum(axis=0)

array([102,  66,  56])

In [53]:
np.arange(0.01, 1.01, 0.01)

array([ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,
        0.1 ,  0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,
        0.19,  0.2 ,  0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,
        0.28,  0.29,  0.3 ,  0.31,  0.32,  0.33,  0.34,  0.35,  0.36,
        0.37,  0.38,  0.39,  0.4 ,  0.41,  0.42,  0.43,  0.44,  0.45,
        0.46,  0.47,  0.48,  0.49,  0.5 ,  0.51,  0.52,  0.53,  0.54,
        0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ,  0.61,  0.62,  0.63,
        0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ,  0.71,  0.72,
        0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ,  0.81,
        0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ,
        0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ])

In [54]:
a.sum(axis=0)

array([102,  66,  56])

In [19]:
import pandas as pd
import numpy as np

In [23]:
df = pd.DataFrame(data=[[np.nan, 5, 6, 7], [0, 1, 2, 3]], index=["a", "b"], columns=["A", "B", "C", "D"])
df

A  B  C  D
a  NaN  5  6  7
b  0.0  1  2  3

In [24]:
df.index.names

FrozenList([None])

In [25]:
df.drop("D", axis=1)

A  B  C
a  NaN  5  6
b  0.0  1  2

In [26]:
df.sort_values(by="C", axis=0)

A  B  C  D
b  0.0  1  2  3
a  NaN  5  6  7

In [27]:
df.dropna()

A  B  C  D
b  0.0  1  2  3

In [28]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [29]:
df.to_csv()

',A,B,C,D\na,,5,6,7\nb,0.0,1,2,3\n'

In [30]:
df.isnull()

A      B      C      D
a   True  False  False  False
b  False  False  False  False

In [35]:
df.to_excel("test.xls")

In [36]:
df2 = pd.DataFrame(data={"A": [np.nan, 2, 4, 3], 
                         "B": [7, 5, 2, 4],
                         "C": [2, 5, 3, 4]})
df2

A  B  C
0  NaN  7  2
1  2.0  5  5
2  4.0  2  3
3  3.0  4  4

In [42]:
df3 = pd.DataFrame(data=[[1, 2, np.nan], [3, np.nan, 5]], index=[0, 1], columns=["A", "B", "C"])
df3

A    B    C
0  1  2.0  NaN
1  3  NaN  5.0

In [43]:
!ls

Excel_Sample.xlsx
example
example_out
multi_index_example
sandbox.ipynb
section_5_python_for_data_analysis_numpy.ipynb
section_5_python_for_data_analysis_numpy_exercises.ipynb
section_6_python_for_data_analysis_pandas.ipynb
test.xls


In [45]:
pd.read_csv("example")

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

df

In [49]:
df.sort_values(by="C", axis=0)

A  B  C  D
b  0.0  1  2  3
a  NaN  5  6  7

In [51]:
df.dropna(thresh=2)

A  B  C  D
a  NaN  5  6  7
b  0.0  1  2  3

In [52]:
df.to_csv("xxx.csv")

In [53]:
!ls

Excel_Sample.xlsx
example
example_out
multi_index_example
sandbox.ipynb
section_5_python_for_data_analysis_numpy.ipynb
section_5_python_for_data_analysis_numpy_exercises.ipynb
section_6_python_for_data_analysis_pandas.ipynb
test.xls
xxx.csv


In [54]:
df.isnull()

A      B      C      D
a   True  False  False  False
b  False  False  False  False

In [56]:
df3 = pd.DataFrame(data={"A": [1, 2, 3],
                         "B": [4, 5, 6],
                         "C": [7, 8, 9]}, index=[0, 1, 2], columns=["A", "B", "C"])

In [57]:
df3

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [59]:
df3.to_excel("df3.xls")

In [62]:
s = pd.Series(data=np.arange(3), index=["a", "b", "c"])
s

a    0
b    1
c    2
dtype: int64

In [63]:
!ls

Excel_Sample.xlsx
df3.xls
example
example_out
multi_index_example
sandbox.ipynb
section_5_python_for_data_analysis_numpy.ipynb
section_5_python_for_data_analysis_numpy_exercises.ipynb
section_6_python_for_data_analysis_pandas.ipynb
test.xls
xxx.csv


In [64]:
pd.read_excel("test.xls")

A  B  C  D
a  NaN  5  6  7
b  0.0  1  2  3

In [66]:
df3 = pd.DataFrame(data=np.random.rand(3, 4), index=["a", "b", "c"], columns=["A", "B", "C", "D"])

df3

A         B         C         D
a  0.899269  0.924372  0.976124  0.412294
b  0.135188  0.044805  0.471173  0.663355
c  0.196076  0.790786  0.753146  0.146054

In [67]:
df3.drop("a", axis=0)

A         B         C         D
b  0.135188  0.044805  0.471173  0.663355
c  0.196076  0.790786  0.753146  0.146054

In [68]:
pd.DataFrame(data=[[1, 2, np.nan], [3, np.nan, 5]], index=[0, 1], columns=["A", "B", "C"])

A    B    C
0  1  2.0  NaN
1  3  NaN  5.0

In [70]:
df[df>2]

A    B    C  D
a NaN  5.0  6.0  7
b NaN  NaN  NaN  3

In [73]:
df.loc["a", "A"]

nan

In [74]:
df.sort_values(by="A", axis=0)

A  B  C  D
b  0.0  1  2  3
a  NaN  5  6  7

In [76]:
df.isnull()

A      B      C      D
a   True  False  False  False
b  False  False  False  False

In [77]:
df.loc["a", "A"]

nan

In [78]:
df[df["B"] > 1]

A  B  C  D
a NaN  5  6  7

In [79]:
df[(df["B"] > 3) & (df["C"] < 2)]

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [80]:
df.iloc[1]

A    0.0
B    1.0
C    2.0
D    3.0
Name: b, dtype: float64

In [81]:
df.reset_index()

index    A  B  C  D
0     a  NaN  5  6  7
1     b  0.0  1  2  3

In [83]:
upper = ["G1", "G1", "G1", "G2", "G2", "G2"]
lower = [1, 2, 3, 1, 2, 3]

hier_index = list(zip(upper, lower))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [84]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [85]:
df.isnull()

A      B      C      D
a   True  False  False  False
b  False  False  False  False

In [89]:
df4 = pd.DataFrame(data=np.random.rand(6, 2), index=hier_index, columns=["A", "B"])
df4

A         B
G1 1  0.474047  0.060399
   2  0.345852  0.255957
   3  0.705751  0.009785
G2 1  0.929132  0.800762
   2  0.966311  0.394509
   3  0.169985  0.955967

In [92]:
df4.loc["G1"].loc[1]

A    0.474047
B    0.060399
Name: 1, dtype: float64

In [93]:
data = {"Company": ["GOOG", "GOOG", "MSFT", "MSFT", "FB", "FB"],
        "Person": ["Sam", "Charlie", "Amy", "Vanessa", "Carl", "Sarah"],
        "Sales": [200, 120, 340, 124, 243, 350]}
df5 = pd.DataFrame(data)
df5


Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [96]:
groups = df5.groupby("Company")
groups.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [101]:
df5.groupby("Company").mean().loc["FB"]

Sales    296.5
Name: FB, dtype: float64

In [102]:
ser1 = pd.Series([1, 2, 3, 4], index=["USA", "Germany", "USSR", "Japan"])

In [104]:
ser1["USA"]

1

In [105]:
ser1 = pd.Series(data=[1, 2, 3, 4], index=["USA", "Poland", "Germany", "Poland"])

In [106]:
ser1

USA        1
Poland     2
Germany    3
Poland     4
dtype: int64

In [107]:
ser1 + ser1

USA        2
Poland     4
Germany    6
Poland     8
dtype: int64

In [108]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [109]:
left

A   B key1 key2
0  A0  B0   K0   K0
1  A1  B1   K0   K1
2  A2  B2   K1   K0
3  A3  B3   K2   K1

In [110]:
right

C   D key1 key2
0  C0  D0   K0   K0
1  C1  D1   K1   K0
2  C2  D2   K1   K0
3  C3  D3   K2   K0

In [112]:
pd.merge(left, right, how="left", on=["key1", "key2"])

A   B key1 key2    C    D
0  A0  B0   K0   K0   C0   D0
1  A1  B1   K0   K1  NaN  NaN
2  A2  B2   K1   K0   C1   D1
3  A2  B2   K1   K0   C2   D2
4  A3  B3   K2   K1  NaN  NaN

In [114]:
s = pd.Series(data=[1, 2, 3, 4], index=["a", "b", "c", "D"])

In [115]:
s["a"]

1

In [116]:
np.random.seed(101)
f = pd.DataFrame(np.random.randn(5, 4), index=["A", "B", "C", "D", "E"], columns=["W", "X", "Y", "Z"])
f


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [117]:
np.random.seed(101)
df = pd.DataFrame(np.random.randn(5, 4), index=["A", "B", "C", "D", "E"], columns=["W", "X", "Y", "Z"])
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [118]:
np.random.seed(101)
df3 = pd.DataFrame(np.random.randn(5, 4), index=["A", "B", "C", "D", "E"], columns=["W", "X", "Y", "Z"])
df3


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [121]:
df3[df3['W'] < 0]['Y']

C    0.528813
Name: Y, dtype: float64

In [122]:
pd.merge(left, right, on=["key1", "key2"], how="left")

A   B key1 key2    C    D
0  A0  B0   K0   K0   C0   D0
1  A1  B1   K0   K1  NaN  NaN
2  A2  B2   K1   K0   C1   D1
3  A2  B2   K1   K0   C2   D2
4  A3  B3   K2   K1  NaN  NaN

In [124]:
df[["W", "X"]]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [126]:
top = ["G1", "G1", "G1", "G2", "G2", "G2"]
bottom = [1, 2, 3, 1, 2, 3]
hier_idx = list(zip(top, bottom))
hier_idx

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [129]:
hier_idx = pd.MultiIndex.from_tuples(hier_idx)
df4 = pd.DataFrame(data=np.random.rand(6, 2), index=hier_idx)

In [130]:
df4

0         1
G1 1  0.734819  0.541962
   2  0.913154  0.807920
   3  0.402998  0.357224
G2 1  0.952877  0.343632
   2  0.865100  0.830278
   3  0.538161  0.922469

In [131]:
df2 = pd.DataFrame(data=[[1, 2, 3], [4, 5, 6]], columns=["A", "B", "C"])
df2

A  B  C
0  1  2  3
1  4  5  6

In [132]:
df2.sum(axis=0)

A    5
B    7
C    9
dtype: int64

In [133]:
df2.sum(axis=1)

0     6
1    15
dtype: int64

In [134]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [136]:
df3[df3["W"] > 1]

W         X         Y         Z
A  2.70685  0.628133  0.907969  0.503826

In [139]:
df3['W'].value_counts()

 0.651118    1
 0.190794    1
 2.706850    1
 0.188695    1
-2.018168    1
Name: W, dtype: int64

In [142]:
df3["A"] = [1, 2, 3, 4, 5]
df3

W         X         Y         Z  A
A  2.706850  0.628133  0.907969  0.503826  1
B  0.651118 -0.319318 -0.848077  0.605965  2
C -2.018168  0.740122  0.528813 -0.589001  3
D  0.188695 -0.758872 -0.933237  0.955057  4
E  0.190794  1.978757  2.605967  0.683509  5

In [148]:
df4.index.names = ["Group", "No."]
df4

0         1
Group No.                    
G1    1    0.734819  0.541962
      2    0.913154  0.807920
      3    0.402998  0.357224
G2    1    0.952877  0.343632
      2    0.865100  0.830278
      3    0.538161  0.922469

In [152]:
df4

0         1
Group No.                    
G1    1    0.734819  0.541962
      2    0.913154  0.807920
      3    0.402998  0.357224
G2    1    0.952877  0.343632
      2    0.865100  0.830278
      3    0.538161  0.922469

In [156]:
df6 = pd.DataFrame({"A": [1, 2, np.nan],
                   "B": [5, np.nan, np.nan],
                   "C": [1, 2, 3]})
df6

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [157]:
df6.fillna(4)

A    B  C
0  1.0  5.0  1
1  2.0  4.0  2
2  4.0  4.0  3

In [158]:
df6.apply(abs)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [169]:
df5['Company'].nunique()

3

In [170]:
left

A   B key1 key2
0  A0  B0   K0   K0
1  A1  B1   K0   K1
2  A2  B2   K1   K0
3  A3  B3   K2   K1

In [172]:
pd.merge(left, right, on=["key1", "key2"], how="right")

A    B key1 key2   C   D
0   A0   B0   K0   K0  C0  D0
1   A2   B2   K1   K0  C1  D1
2   A2   B2   K1   K0  C2  D2
3  NaN  NaN   K2   K0  C3  D3

In [173]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [174]:
left.join(right, how="left")

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [179]:
df2['A'].value_counts()

1    1
4    1
Name: A, dtype: int64

In [180]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})


In [181]:
pd.merge(left, right, on=["key1", "key2"], how="outer")

A    B key1 key2    C    D
0   A0   B0   K0   K0   C0   D0
1   A1   B1   K0   K1  NaN  NaN
2   A2   B2   K1   K0   C1   D1
3   A2   B2   K1   K0   C2   D2
4   A3   B3   K2   K1  NaN  NaN
5  NaN  NaN   K2   K0   C3   D3

In [182]:
pd.Series(data={"a": 10, "b": 20, "c": 30})

a    10
b    20
c    30
dtype: int64

In [183]:
data = {"Company": ["GOOG", "GOOG", "MSFT", "MSFT", "FB", "FB"],
        "Person": ["Sam", "Charlie", "Amy", "Vanessa", "Carl", "Sarah"],
        "Sales": [200, 120, 340, 124, 243, 350]}
df = pd.DataFrame(data)
df


Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [184]:
df.groupby("Company").mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [187]:
df.drop("Sales", axis=1)

Company   Person
0    GOOG      Sam
1    GOOG  Charlie
2    MSFT      Amy
3    MSFT  Vanessa
4      FB     Carl
5      FB    Sarah

In [189]:
df = pd.DataFrame({"A": [1, 2, np.nan],
                   "B": [5, np.nan, np.nan],
                   "C": [1, 2, 3]})
df.fillna("s")

A  B  C
0  1  5  1
1  2  s  2
2  s  s  3

In [190]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [193]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [2]:
import pandas as pd
data = {"Company": ["GOOG", "GOOG", "MSFT", "MSFT", "FB", "FB"],
        "Person": ["Sam", "Charlie", "Amy", "Vanessa", "Carl", "Sarah"],
        "Sales": [200, 120, 340, 124, 243, 350]}
df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [2]:
import pandas as pd
df = pd.DataFrame({"col1": [1, 2, 3, 4], "col2": [444, 555, 666, 444], "col3": ["abc", "def", "ghi", "xyz"]})
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [5]:
df.count(axis=1)

0    3
1    3
2    3
3    3
dtype: int64

In [8]:
df["col1"].unique()

array([1, 2, 3, 4])

In [ ]:
pd.read_csv

In [9]:
ser1 = pd.Series([1, 2, 3, 4], index=["USA", "Germany", "USSR", "Japan"])

In [11]:
ser1["USA"]

1

In [22]:
import numpy as np
df3 = pd.DataFrame({"A": [1, 2, np.nan],
                   "B": [5, np.nan, np.nan],
                   "C": [1, 2, 3]})
df3

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [14]:
df2.fillna("S")

A  B  C
0  1  5  1
1  2  S  2
2  S  S  3

In [15]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [16]:
df["col1"].nunique()

4

In [ ]:
df.ap

In [17]:
df1 = pd.DataFrame({"A": ["A0", "A1", "A2", "A3"],
                    "B": ["B0", "B1", "B2", "B3"],
                    "C": ["C0", "C1", "C2", "C3"],
                    "D": ["D0", "D1", "D2", "D3"]},
                  index=[0, 1, 2, 3])

df2 = pd.DataFrame({"A": ["A4", "A5", "A6", "A7"],
                    "B": ["B4", "B5", "B6", "B7"],
                    "C": ["C4", "C5", "C6", "C7"],
                    "D": ["D4", "D5", "D6", "D7"]},
                  index=[4, 5, 6, 7])

In [20]:
pd.concat([df1, df2], axis=1)

A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [25]:
df3.dropna(axis=1)

C
0  1
1  2
2  3

In [26]:
ser2 = pd.Series(data=[1, 2, 3, 4], index=["a", "b", "c", "d"])

In [27]:
ser2

a    1
b    2
c    3
d    4
dtype: int64

In [28]:
np.random.seed(101)
df4 = pd.DataFrame(np.random.randn(5, 4), index=["A", "B", "C", "D", "E"], columns=["W", "X", "Y", "Z"])
df4

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
df4.loc["A", "W"]

2.7068498393999381

In [34]:
df4.sum(axis=1)

A    4.746778
B    0.089688
C   -1.338233
D   -0.548357
E    5.459028
dtype: float64

In [36]:
df4[(df4["X"] > 0) & (df4["Y"] < 0)]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [38]:
df3.fillna(2)

A    B  C
0  1.0  5.0  1
1  2.0  2.0  2
2  2.0  2.0  3

In [40]:
df3.drop("A", axis=1)

B  C
0  5.0  1
1  NaN  2
2  NaN  3

In [41]:
pd.DataFrame(data={"A": [1, 2, 3], 
                   "B": [4, 5, 6],
                   "C": [7, 8, 9]})

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [44]:
df3.dropna(axis=1)

C
0  1
1  2
2  3

In [53]:
df4.sort_values(by="C", axis=1)

W         Z         Y         X
A  2.706850  0.503826  0.907969  0.628133
B  0.651118  0.605965 -0.848077 -0.319318
C -2.018168 -0.589001  0.528813  0.740122
D  0.188695  0.955057 -0.933237 -0.758872
E  0.190794  0.683509  2.605967  1.978757

In [54]:
data = {"Company": ["GOOG", "GOOG", "MSFT", "MSFT", "FB", "FB"],
        "Person": ["Sam", "Charlie", "Amy", "Vanessa", "Carl", "Sarah"],
        "Sales": [200, 120, 340, 124, 243, 350]}
df4 = pd.DataFrame(data)
df4


Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [57]:
df4.groupby("Company").mean().loc["FB"]

Sales    296.5
Name: FB, dtype: float64

In [58]:
df4.to_csv("xxx")

In [59]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [60]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [61]:
pd.concat([df1, df2], axis=0)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [63]:
df["col4"] = [1, 2, 3, 4]

In [64]:
df

col1  col2 col3  col4
0     1   444  abc     1
1     2   555  def     2
2     3   666  ghi     3
3     4   444  xyz     4

In [65]:
df.set_index("col4")

col1  col2 col3
col4                 
1        1   444  abc
2        2   555  def
3        3   666  ghi
4        4   444  xyz

In [66]:
df

col1  col2 col3  col4
0     1   444  abc     1
1     2   555  def     2
2     3   666  ghi     3
3     4   444  xyz     4

In [67]:
df3.isnull()

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [70]:
df3.dropna(axis=1)

C
0  1
1  2
2  3

In [72]:
df3.drop(0, axis=0)

A   B  C
1  2.0 NaN  2
2  NaN NaN  3

In [75]:
df4.groupby("Company").describe().loc["GOOG"]

Sales
count    2.000000
mean   160.000000
std     56.568542
min    120.000000
25%    140.000000
50%    160.000000
75%    180.000000
max    200.000000

In [ ]:
df.to_