In [19]:
import pandas as pd

In [3]:
s = pd.Series([1, 2, 3, 4], index=["a", "b", "c", "d"])
s

a    1
b    2
c    3
d    4
dtype: int64

In [6]:
ss = pd.Series({"a": 1, "b": 2, "c": "a"})

ss

a    1
b    2
c    a
dtype: object

In [9]:
ss.loc["a"]

1

In [10]:
ser1 = pd.Series([1, 2, 3, 4], index=["USA", "Germany", "USSR", "Japan"])

In [11]:
ser2 = pd.Series([1, 2, 5, 4], index = ["USA", "Germany", "Italy", "Japan"])

In [12]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [17]:
import numpy as np

In [26]:
a = pd.DataFrame(data=np.random.rand(3, 2), index=["a", "b", "c"], columns=["A", "B",])

In [24]:
a

0         1
a  0.757137  0.256945
b  0.483537  0.746723
c  0.707860  0.608355

In [28]:
a["A"]

a    0.802425
b    0.082821
c    0.105348
Name: A, dtype: float64

In [29]:
a[["A", "B"]]

A         B
a  0.802425  0.571205
b  0.082821  0.701624
c  0.105348  0.648387

In [30]:
a["C"] = [1, 2, 3]

In [31]:
a

A         B  C
a  0.802425  0.571205  1
b  0.082821  0.701624  2
c  0.105348  0.648387  3

In [32]:
a.drop("C", axis=1)

A         B
a  0.802425  0.571205
b  0.082821  0.701624
c  0.105348  0.648387

In [33]:
a.drop("a", axis=0)

A         B  C
b  0.082821  0.701624  2
c  0.105348  0.648387  3

In [34]:
a.loc["a"]

A    0.802425
B    0.571205
C    1.000000
Name: a, dtype: float64

In [35]:
a.iloc[2]

A    0.105348
B    0.648387
C    3.000000
Name: c, dtype: float64

In [37]:
a.loc["a", "A"]

0.80242519226860387

In [38]:
np.random.seed(101)
df = pd.DataFrame(np.random.randn(5, 4), index=["A", "B", "C", "D", "E"], columns=["W", "X", "Y", "Z"])
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [41]:
df[df["W"] > 2]

W         X         Y         Z
A  2.70685  0.628133  0.907969  0.503826

In [48]:
df[(df["W"] > 0) & (df["Y"] > 0)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
E  0.190794  1.978757  2.605967  0.683509

In [49]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [50]:
df.set_index("W")

X         Y         Z
W                                      
 2.706850  0.628133  0.907969  0.503826
 0.651118 -0.319318 -0.848077  0.605965
-2.018168  0.740122  0.528813 -0.589001
 0.188695 -0.758872 -0.933237  0.955057
 0.190794  1.978757  2.605967  0.683509

In [51]:
pd.DataFrame(data=np.random.rand(2, 3), index=["A", "B"], columns=["C", "D", "E"])

C         D         E
A  0.734819  0.541962  0.913154
B  0.807920  0.402998  0.357224

In [52]:
df2 = pd.DataFrame({"A": [1, 2, np.nan],
                              "B": [5, np.nan, np.nan],
                              "C": [1, 2, 3]})
df2

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [56]:
df2.dropna(axis=1)

C
0  1
1  2
2  3

In [57]:
df.drop("X", axis=1)

W         Y         Z
A  2.706850  0.907969  0.503826
B  0.651118 -0.848077  0.605965
C -2.018168  0.528813 -0.589001
D  0.188695 -0.933237  0.955057
E  0.190794  2.605967  0.683509

In [59]:
df.drop("A", axis=0)

W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [60]:
df.loc["B", "W"]

0.6511179479432686

In [63]:
df2.dropna(axis=0)

A    B  C
0  1.0  5.0  1

In [64]:
df2.dropna(axis=0, thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [65]:
df2.fillna("s")

A  B  C
0  1  5  1
1  2  s  2
2  s  s  3

In [ ]:
df2.fillna(df.mean("axis"))

In [66]:
pd.DataFrame({"A": [1, 2, 3], 
              "B": [4, 5, 6]})

A  B
0  1  4
1  2  5
2  3  6

In [67]:
data = {"Company": ["GOOG", "GOOG", "MSFT", "MSFT", "FB", "FB"],
        "Person": ["Sam", "Charlie", "Amy", "Vanessa", "Carl", "Sarah"],
        "Sales": [200, 120, 340, 124, 243, 350]}
df3 = pd.DataFrame(data)
df3


Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [70]:
df3_grouped = df3.groupby("Company")

In [72]:
df3_grouped.mean().loc["FB"]

Sales    296.5
Name: FB, dtype: float64

In [73]:
df1 = pd.DataFrame({"A": ["A0", "A1", "A2", "A3"],
                    "B": ["B0", "B1", "B2", "B3"],
                    "C": ["C0", "C1", "C2", "C3"],
                    "D": ["D0", "D1", "D2", "D3"]},
                  index=[0, 1, 2, 3])

df2 = pd.DataFrame({"A": ["A4", "A5", "A6", "A7"],
                    "B": ["B4", "B5", "B6", "B7"],
                    "C": ["C4", "C5", "C6", "C7"],
                    "D": ["D4", "D5", "D6", "D7"]},
                  index=[4, 5, 6, 7])

In [74]:
pd.concat([df1, df2], axis=0)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [75]:
df5 = pd.DataFrame({"A": [1, 2, np.nan],
                              "B": [5, np.nan, np.nan],
                              "C": [1, 2, 3]})
df5

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [77]:
df5.dropna()

A    B  C
0  1.0  5.0  1

In [79]:
df5.fillna(5)

A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  5.0  5.0  3

In [80]:
df5.dropna(axis=1)

C
0  1
1  2
2  3

In [81]:
df5.dropna(axis=0)

A    B  C
0  1.0  5.0  1

In [82]:
df.fillna(5)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [83]:
pd.concat([df1, df2], axis=0)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [84]:
left = pd.DataFrame({"key": ["K0", "K1", "K2", "K3"],
                     "A": ["A0", "A1", "A2", "A3"],
                     "B": ["B0", "B1", "B2", "B3"]})

right = pd.DataFrame({"key": ["K0", "K1", "K2", "K3"],
                      "C": ["C0", "C1", "C2", "C3"],
                      "D": ["D0", "D1", "D2", "D3"]})



In [87]:
pd.merge(left, right, on="key", how="inner")

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

In [89]:
df = pd.DataFrame({"col1": [1, 2, 3, 4], "col2": [444, 555, 666, 444], "col3": ["abc", "def", "ghi", "xyz"]})
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [93]:
df["col1"].nunique()

4

In [97]:
df = df.drop("col3", axis=1)

In [98]:
df.apply(lambda x: x + 2)

col1  col2
0     3   446
1     4   557
2     5   668
3     6   446

In [99]:
df["col1"].sum()

10

In [100]:
df.columns

Index(['col1', 'col2'], dtype='object')

In [101]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [105]:
df.sort_values(by="col1", axis=0)

col1  col2
0     1   444
1     2   555
2     3   666
3     4   444

In [109]:
df5.dropna(axis=0)

A    B  C
0  1.0  5.0  1

In [110]:
df5.dropna(axis=0)

A    B  C
0  1.0  5.0  1

In [111]:
df2 = pd.DataFrame(data=[[1, 2, 3], [4, 5, 6]], columns=["A", "B", "C"])
df2

A  B  C
0  1  2  3
1  4  5  6

In [114]:
df2.sum(axis=0)

A    5
B    7
C    9
dtype: int64

In [115]:
df5.fillna(4)

A    B  C
0  1.0  5.0  1
1  2.0  4.0  2
2  4.0  4.0  3

In [120]:
df["col1"].value_counts()

4    1
3    1
2    1
1    1
Name: col1, dtype: int64

In [121]:
df.sort_values(by="col2", axis=0)

col1  col2
0     1   444
3     4   444
1     2   555
2     3   666

In [122]:
df5.dropna(axis=0)

A    B  C
0  1.0  5.0  1

In [125]:
df5[df5.isnull()]

A   B   C
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN

In [2]:
import pandas as pd
s1 = pd.Series([1, 2, 3, 4], index=["a", "b", "c", "d"])
s2 = pd.Series([10, 20, 30, 40], index=["a", "b", "c", "d"])


In [4]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
s2

a    10
b    20
c    30
d    40
dtype: int64

In [6]:
s1 + s2

a    11
b    22
c    33
d    44
dtype: int64

In [7]:
s3 = pd.Series([1, 2, 3, 4], index=["a", "b", "c", "d"])
s4 = pd.Series([10, 20, 30, 40], index=["c", "d", "e", "f"])

In [8]:
s3 + s4

a     NaN
b     NaN
c    13.0
d    24.0
e     NaN
f     NaN
dtype: float64

In [10]:
s5 = pd.Series([1, 2, 3, 4], index=["a", "b", "c", "d"])
s6 = pd.Series([10, 20, 30, 40], index=["e", "f", "g", "h"])
s5 + s6

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
g   NaN
h   NaN
dtype: float64

In [11]:
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)
ridership_df


R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
05-05-11  1608  4802  3932  4477  2705
05-06-11  1576  3933  3909  4979  2685
05-07-11    95   229   255   496   201
05-08-11     2     0     1    27     0
05-09-11  1438  3785  3589  4174  2215
05-10-11  1342  4043  4009  4665  3033

In [12]:
ridership_df.loc[["05-01-11", "05-02-11"]]

R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539

In [14]:
ridership_df.values.sum()

117130

In [16]:
ridership_df.max(axis=1)

05-01-11       5
05-02-11    3877
05-03-11    6461
05-04-11    4787
05-05-11    4802
05-06-11    4979
05-07-11     496
05-08-11      27
05-09-11    4174
05-10-11    4665
dtype: int64

In [17]:
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({"a": [10, 20, 30], "b": [40, 50, 60], 'c': [70, 80, 90]})


In [19]:
df1 + df2

a   b   c
0  11  44  77
1  22  55  88
2  33  66  99

In [20]:
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({"a": [10, 20, 30], "b": [40, 50, 60], 'c': [70, 80, 90]})


In [21]:
df1 + df2

a   b   c
0  11  44  77
1  22  55  88
2  33  66  99

In [22]:
df1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]})
df2 = pd.DataFrame({"d": [10, 20, 30], "c": [40, 50, 60], "b": [70, 80, 90]})
df1 + df2

a   b   c   d
0 NaN  74  47 NaN
1 NaN  85  58 NaN
2 NaN  96  69 NaN

In [23]:
df1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]},
                  index=["row1", "row2", "row3"])
df2 = pd.DataFrame({"a": [10, 20, 30], "b": [40, 50, 60], "c": [70, 80, 90]},
                  index=["row4", "row3", "row2"])
df1 + df2

a     b     c
row1   NaN   NaN   NaN
row2  32.0  65.0  98.0
row3  23.0  56.0  89.0
row4   NaN   NaN   NaN

In [24]:
df1

a  b  c
row1  1  4  7
row2  2  5  8
row3  3  6  9

In [25]:
df1.sum(axis=0)

a     6
b    15
c    24
dtype: int64

In [26]:
df1.sum(axis=1)

row1    12
row2    15
row3    18
dtype: int64

In [27]:
df1.mean(axis=0)

a    2.0
b    5.0
c    8.0
dtype: float64

In [28]:
df1.mean(axis=1)

row1    4.0
row2    5.0
row3    6.0
dtype: float64

In [30]:
df1.mean(axis=1)

row1    4.0
row2    5.0
row3    6.0
dtype: float64

In [31]:
df1

a  b  c
row1  1  4  7
row2  2  5  8
row3  3  6  9

In [33]:
df1.drop("a", axis=1)

b  c
row1  4  7
row2  5  8
row3  6  9

In [35]:
df1.drop("row1", axis=0)

a  b  c
row2  2  5  8
row3  3  6  9

In [37]:
df1.dropna(axis=0)

a  b  c
row1  1  4  7
row2  2  5  8
row3  3  6  9

In [38]:
df1.dropna(axis=1)

a  b  c
row1  1  4  7
row2  2  5  8
row3  3  6  9

In [40]:
df1.sort_values(by="a", axis=0)

a  b  c
row1  1  4  7
row2  2  5  8
row3  3  6  9

In [42]:
df1.sort_values(by="row1", axis=1)

a  b  c
row1  1  4  7
row2  2  5  8
row3  3  6  9

In [43]:
a = pd.DataFrame(data={"A": [0, 1, 2, 3], "B": [4, 5, 6, 7], "C": [8, 9, 10, 11]})

b = pd.DataFrame(data={"B": [44, 5, 6, 77], "D": [0, 1, 2, 3], "E": [8, 9, 10, 11]})



In [44]:
a

A  B   C
0  0  4   8
1  1  5   9
2  2  6  10
3  3  7  11

In [45]:
b

B  D   E
0  44  0   8
1   5  1   9
2   6  2  10
3  77  3  11

In [47]:
pd.concat([a, b], axis=1)

A  B   C   B  D   E
0  0  4   8  44  0   8
1  1  5   9   5  1   9
2  2  6  10   6  2  10
3  3  7  11  77  3  11

In [48]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    "A": [10, 20, 30, 40],
    "B": [50, 60, 70, 80],
    "C": [90, 100, 110, 120],
    "D": [130, 140, 150, 160]
})

In [49]:
df

A   B    C    D
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

In [50]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [51]:
df + s

A   B   C   D   0   1   2   3
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN

In [52]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    "A": [10, 20, 30, 40],
    2: [50, 60, 70, 80],
    3: [90, 100, 110, 120],
    "D": [130, 140, 150, 160]
})


In [53]:
df

A   2    3    D
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

In [54]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [55]:
df + s

//anaconda/lib/python3.6/site-packages/pandas/indexes/base.py:2683: RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  return this.join(other, how=how, return_indexers=return_indexers)


A     2      3   D   0   1
0 NaN  53.0   94.0 NaN NaN NaN
1 NaN  63.0  104.0 NaN NaN NaN
2 NaN  73.0  114.0 NaN NaN NaN
3 NaN  83.0  124.0 NaN NaN NaN

In [60]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({0: [10], 1: [20], 2: [30], 3:[40]})

In [61]:
df

0   1   2   3
0  10  20  30  40

In [62]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [64]:
df + s

0   1   2   3
0  11  22  33  44

In [66]:
import numpy as np

df = pd.DataFrame(np.random.randn(5, 4), index=["A", "B", "C", "D", "E"], columns=["W", "X", "Y", "Z"])
df

W         X         Y         Z
A -0.034661 -0.929920 -0.125567  0.154979
B  0.127397 -1.879021 -0.504618  0.733113
C  0.403053 -0.709239 -0.774373 -1.216787
D  1.133038  0.255130 -0.059001 -0.648223
E  1.036641 -1.445137 -0.888665 -0.959446

In [68]:
df["W"].value_counts()

 0.403053    1
 1.036641    1
 0.127397    1
-0.034661    1
 1.133038    1
Name: W, dtype: int64

In [69]:
df

W         X         Y         Z
A -0.034661 -0.929920 -0.125567  0.154979
B  0.127397 -1.879021 -0.504618  0.733113
C  0.403053 -0.709239 -0.774373 -1.216787
D  1.133038  0.255130 -0.059001 -0.648223
E  1.036641 -1.445137 -0.888665 -0.959446

In [70]:
df.sort_values(by="W", axis=0)

W         X         Y         Z
A -0.034661 -0.929920 -0.125567  0.154979
B  0.127397 -1.879021 -0.504618  0.733113
C  0.403053 -0.709239 -0.774373 -1.216787
E  1.036641 -1.445137 -0.888665 -0.959446
D  1.133038  0.255130 -0.059001 -0.648223

In [71]:
np.arange(0, 100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [72]:
a = np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]
a


array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [73]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [74]:
a[0, 3:5]

array([3, 4])

In [75]:
np.random.rand(2, 3)

array([[ 0.22556271,  0.64276311,  0.21132408],
       [ 0.57756053,  0.78620626,  0.1024611 ]])

In [76]:
a[:] = 100

In [77]:
a

array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

In [78]:
np.linspace(0.1, 1, 11)

array([ 0.1 ,  0.19,  0.28,  0.37,  0.46,  0.55,  0.64,  0.73,  0.82,
        0.91,  1.  ])

In [79]:

np.arange(1, 100, 2)[::-1]

array([99, 97, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67,
       65, 63, 61, 59, 57, 55, 53, 51, 49, 47, 45, 43, 41, 39, 37, 35, 33,
       31, 29, 27, 25, 23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [82]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [81]:
a = np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [83]:
a[[0, 1, 2, 3, 4], [1, 2, 3, 4, 5]]

array([ 1, 12, 23, 34, 45])

In [84]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [86]:
np.arange(0, 6) + np.arange(0, 51, 10)[:, np.newaxis]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [87]:
np.arange(0, 10, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9])

In [89]:
np.ones((2, 2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [91]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [93]:
a.sum(axis=0)

array([150, 156, 162, 168, 174, 180])

In [94]:
np.zeros((2, 2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [95]:
np.arange(0, 6) + np.arange(0, 51, 10)[:, np.newaxis]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [96]:
a[0, 3:5]

array([3, 4])

In [97]:
np.linspace(0, 0.8, 5)

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

In [98]:
np.arange(0, 6) + np.arange(0, 51, 10)[:, np.newaxis]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [99]:
np.ones((2, 2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [101]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [102]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [104]:
a.sort(axis=0)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [105]:
a[3:, [0, 2, 5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [106]:
a[2, [0, 2, 5]]

array([20, 22, 25])

In [107]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [109]:
a.min()

0

In [110]:
np.linspace(0.1, 1, 10)

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

In [112]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [113]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15, 20, 21, 22, 23, 24,
       25, 30, 31, 32, 33, 34, 35, 40, 41, 42, 43, 44, 45, 50, 51, 52, 53,
       54, 55])

In [114]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [117]:
a.mean(axis=1)

array([  2.5,  12.5,  22.5,  32.5,  42.5,  52.5])

In [118]:
a.sort(axis=0)

In [121]:
len(a)

6

In [122]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [123]:
np.sort(a, axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [124]:
a[:, 2:3]

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52]])

In [125]:
np.argsort(a)

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [126]:

a.ndim

2

In [127]:
np.random.shuffle(a)

In [129]:
a.sort(axis=1)

In [130]:
a

array([[10, 11, 12, 13, 14, 15],
       [40, 41, 42, 43, 44, 45],
       [ 0,  1,  2,  3,  4,  5],
       [30, 31, 32, 33, 34, 35],
       [50, 51, 52, 53, 54, 55],
       [20, 21, 22, 23, 24, 25]])

In [131]:
np.linspace(0, 1, 6)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [132]:
mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])

In [133]:
mileposts - mileposts[:, np.newaxis]

array([[    0,   198,   303,   736,   871,  1175,  1475,  1544,  1913,
         2448],
       [ -198,     0,   105,   538,   673,   977,  1277,  1346,  1715,
         2250],
       [ -303,  -105,     0,   433,   568,   872,  1172,  1241,  1610,
         2145],
       [ -736,  -538,  -433,     0,   135,   439,   739,   808,  1177,
         1712],
       [ -871,  -673,  -568,  -135,     0,   304,   604,   673,  1042,
         1577],
       [-1175,  -977,  -872,  -439,  -304,     0,   300,   369,   738,
         1273],
       [-1475, -1277, -1172,  -739,  -604,  -300,     0,    69,   438,
          973],
       [-1544, -1346, -1241,  -808,  -673,  -369,   -69,     0,   369,
          904],
       [-1913, -1715, -1610, -1177, -1042,  -738,  -438,  -369,     0,
          535],
       [-2448, -2250, -2145, -1712, -1577, -1273,  -973,  -904,  -535,
            0]])

In [138]:
np.sort(a.ravel())

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15, 20, 21, 22, 23, 24,
       25, 30, 31, 32, 33, 34, 35, 40, 41, 42, 43, 44, 45, 50, 51, 52, 53,
       54, 55])

In [1]:
import numpy as np

np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [3]:
np.ones(9).reshape(3, 3)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [5]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])