In [2]:
import numpy as np

In [3]:
a = [1, 2, 3]
a

[1, 2, 3]

In [4]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.zeros((3, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [19]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [20]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.linspace(0, 10, 100)

array([  0.        ,   0.1010101 ,   0.2020202 ,   0.3030303 ,
         0.4040404 ,   0.50505051,   0.60606061,   0.70707071,
         0.80808081,   0.90909091,   1.01010101,   1.11111111,
         1.21212121,   1.31313131,   1.41414141,   1.51515152,
         1.61616162,   1.71717172,   1.81818182,   1.91919192,
         2.02020202,   2.12121212,   2.22222222,   2.32323232,
         2.42424242,   2.52525253,   2.62626263,   2.72727273,
         2.82828283,   2.92929293,   3.03030303,   3.13131313,
         3.23232323,   3.33333333,   3.43434343,   3.53535354,
         3.63636364,   3.73737374,   3.83838384,   3.93939394,
         4.04040404,   4.14141414,   4.24242424,   4.34343434,
         4.44444444,   4.54545455,   4.64646465,   4.74747475,
         4.84848485,   4.94949495,   5.05050505,   5.15151515,
         5.25252525,   5.35353535,   5.45454545,   5.55555556,
         5.65656566,   5.75757576,   5.85858586,   5.95959596,
         6.06060606,   6.16161616,   6.26262626,   6.36

In [25]:
np.eye(1)

array([[ 1.]])

In [28]:
np.random.rand(2, 2)

array([[ 0.43023496,  0.20271238],
       [ 0.91347807,  0.68689034]])

In [31]:
np.random.randn(3, 3)

array([[ 0.90244618,  3.30966402,  0.08448253],
       [ 0.46404231,  0.54468484, -0.86810442],
       [ 0.07190871,  0.37199029,  0.90592918]])

In [44]:
np.random.randint(1, 100, 10)

array([89, 57, 82, 75, 79, 70, 22, 80,  4, 43])

In [45]:
np.random.randint(1, 100)

80

In [58]:
arr = np.arange(25)
b = arr.reshape(5, 5)

b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
b.sum(axis=0)

array([50, 55, 60, 65, 70])

In [60]:
b.shape

(5, 5)

In [61]:
b.dtype

dtype('int64')

In [62]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr[8]

8

In [65]:
arr[:3]

array([0, 1, 2])

In [67]:
arr[0:3] = 10

arr

array([10, 10, 10,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
ll = [1, 2, 3, 4]
l = ll[2:4]
l

[3, 4]

In [70]:
l[0] = 55
l

[55, 4]

In [71]:
ll

[1, 2, 3, 4]

In [74]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [75]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [76]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [77]:
arr_copy = arr.copy()

In [81]:
arr = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [82]:
arr[1]

array([20, 25, 30])

In [83]:
arr[0, 0]

5

In [87]:
arr[1:, 1:]

array([[25, 30],
       [40, 45]])

In [89]:
arr2 = np.zeros((10, 10))
arr2

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [90]:
arr2.shape

(10, 10)

In [93]:
arr2[[2, 3, 4]]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [95]:
arr = np.arange(1, 11)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [97]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [6]:
%timeit np.arange(50).reshape(5, 10)

The slowest run took 2324.21 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 941 ns per loop


In [99]:
arr = np.arange(0, 10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
arr + arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [101]:
arr * arr 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [102]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [103]:
arr / arr

//anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [104]:
1 / arr

//anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111])

In [105]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [106]:
arr * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [107]:
1 / 0

ZeroDivisionError: division by zero

In [108]:
arr / arr

//anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [109]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [110]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [111]:
np.max(arr)

9

In [112]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [113]:
np.log(arr)

//anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

In [8]:
%timeit np.eye(3, 3)

The slowest run took 80.73 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.02 µs per loop


In [10]:
np.linspace(0.01, 1, 100).reshape((10, 10))

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [11]:
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [12]:
np.random.randn(25)

array([ 1.31612074, -0.45614616,  0.54863832,  0.3483516 , -0.33861627,
        0.41508076, -0.52189112, -1.53554977,  1.3470269 ,  0.06390593,
       -1.39890821, -0.93061945, -1.21177808, -0.03887653, -0.78471298,
        1.43806442,  0.23846861, -1.97486683, -0.13873605, -0.93527634,
       -0.63680007,  0.60250234, -0.44679825, -0.41083221, -0.75684623])

In [13]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [15]:
a = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])


In [19]:
a[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [20]:
a.copy()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
np.ones((10, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [25]:
a.argmin()

0

In [27]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [29]:
np.random.rand()

0.8416504287912646

In [31]:
a = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
a[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [37]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [40]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
arr_2d[1, 1:4]

array([11, 12, 13])

In [44]:
arr_2d[:, 2]

array([ 2, 12, 22, 32, 42])

In [47]:
arr_2d[1:4, 0:2]

array([[10, 11],
       [20, 21],
       [30, 31]])

In [48]:
arr_2d[2, 5:8]

array([25, 26, 27])

In [49]:
arr_2d[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [51]:
arr_2d[:, 6]

array([ 6, 16, 26, 36, 46])

In [52]:
arr_2d[3:5, 2:4]

array([[32, 33],
       [42, 43]])

In [53]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [56]:
a[3, 4]

20

In [58]:
np.arange(25).reshape(5, 5).shape

(5, 5)

In [59]:
np.linspace(0, 1, 20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [62]:
np.random.randint(0, 10, (3, 3))

array([[0, 6, 0],
       [0, 8, 9],
       [2, 3, 0]])

In [63]:
np.linspace(0, 10, 3)

array([  0.,   5.,  10.])

In [64]:
np.linspace(0, 10, 50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [66]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [67]:
a = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [70]:
a[2:5, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [71]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [72]:
a[4]

array([21, 22, 23, 24, 25])

In [73]:
a[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [74]:
a.dtype

dtype('int64')

In [77]:
np.random.rand(2, 2)

array([[ 0.96757181,  0.03150235],
       [ 0.55431413,  0.12661033]])

In [79]:
np.arange(0, 50).reshape(5, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])