In [1]:
l = [1, 2, 3, 4]

In [2]:
import numpy as np

In [3]:
np.array(l)

array([1, 2, 3, 4])

In [4]:
ll = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
ll

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(ll)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0, 10, 5)

array([0, 5])

In [14]:
np.zeros((10, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [15]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [20]:
np.linspace(0, 100, 50)

array([   0.        ,    2.04081633,    4.08163265,    6.12244898,
          8.16326531,   10.20408163,   12.24489796,   14.28571429,
         16.32653061,   18.36734694,   20.40816327,   22.44897959,
         24.48979592,   26.53061224,   28.57142857,   30.6122449 ,
         32.65306122,   34.69387755,   36.73469388,   38.7755102 ,
         40.81632653,   42.85714286,   44.89795918,   46.93877551,
         48.97959184,   51.02040816,   53.06122449,   55.10204082,
         57.14285714,   59.18367347,   61.2244898 ,   63.26530612,
         65.30612245,   67.34693878,   69.3877551 ,   71.42857143,
         73.46938776,   75.51020408,   77.55102041,   79.59183673,
         81.63265306,   83.67346939,   85.71428571,   87.75510204,
         89.79591837,   91.83673469,   93.87755102,   95.91836735,
         97.95918367,  100.        ])

In [25]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [28]:
np.random.rand(10, 10)

array([[ 0.09940362,  0.82650344,  0.38231356,  0.12231777,  0.40349355,
         0.39243457,  0.56128785,  0.43016119,  0.02083132,  0.80878597],
       [ 0.21036704,  0.18636667,  0.99842365,  0.0196555 ,  0.51209265,
         0.77895061,  0.62396634,  0.04115877,  0.75959679,  0.60646078],
       [ 0.98495806,  0.9446111 ,  0.6556061 ,  0.8591502 ,  0.90060229,
         0.86496676,  0.5550354 ,  0.46227747,  0.74752068,  0.54823448],
       [ 0.7380309 ,  0.91911337,  0.11787996,  0.36139662,  0.13965377,
         0.50107997,  0.60448748,  0.57649992,  0.81129816,  0.91264228],
       [ 0.29365893,  0.49941305,  0.13921232,  0.97576733,  0.65749844,
         0.93021567,  0.80936501,  0.64265355,  0.91412396,  0.78830836],
       [ 0.40491363,  0.04470779,  0.66406377,  0.62702109,  0.72020794,
         0.66610963,  0.7716199 ,  0.20424796,  0.9626199 ,  0.62679579],
       [ 0.45983624,  0.3032012 ,  0.19964762,  0.67206186,  0.44759025,
         0.64269007,  0.72497379,  0.26592357

In [29]:
np.random.randn(10, 10)

array([[-0.39482638,  0.55845575, -0.19616169,  0.99598649, -1.08141215,
        -1.5382976 ,  0.57398905,  0.2819025 ,  0.70309413, -0.59572852],
       [ 0.28081226, -0.96031716,  0.17260884,  1.16145549,  1.46617344,
        -0.76156983,  2.7944533 , -0.8744879 ,  1.83141942, -1.89241425],
       [-0.14971495,  0.12328728,  0.19750746,  1.33498054,  0.1929694 ,
         0.5615059 ,  2.9260283 , -0.62535122, -0.51825376, -0.92755683],
       [ 0.01992417,  0.27431662, -2.73321207,  2.15383191,  1.769861  ,
         1.22058109,  0.99931403,  0.69296826,  1.05074847,  0.4048553 ],
       [-0.40058084,  0.3462027 , -0.96371189,  0.15996549, -0.75930224,
        -0.55828634, -0.47650394,  0.62688915, -1.00199286, -0.32566705],
       [ 1.44009747,  1.09170471,  0.10783471,  0.38124685, -0.86201522,
         0.26861301, -1.42578244,  0.40823254,  1.59645557,  0.16322746],
       [-0.08472306, -0.28590195,  1.23593946, -0.15485134, -0.67403941,
         0.9386583 , -0.17270189, -0.64080618

In [45]:
np.random.randint(0, 10, 100).reshape

dtype('int64')

In [60]:
arr = np.arange(0, 100)
arr2 = arr.reshape(10, 10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
arr[0]

0

In [65]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

In [71]:
s = arr[:10].copy()
s

array([777, 777, 777, 777, 777, 777, 777, 777, 777, 777])

In [72]:
s[:] = 999
s

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [73]:
arr

array([777, 777, 777, 777, 777, 777, 777, 777, 777, 777,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

In [92]:
arr2

array([[777, 777, 777, 777, 777, 777, 777, 777, 777, 777],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [83]:
arr2[:,8:]

array([[777, 777],
       [ 18,  19],
       [ 28,  29],
       [ 38,  39],
       [ 48,  49],
       [ 58,  59],
       [ 68,  69],
       [ 78,  79],
       [ 88,  89],
       [ 98,  99]])

In [88]:
arr = np.arange(0, 10)

In [89]:
s = arr[:5]

In [90]:
s[:] = 100
s

array([100, 100, 100, 100, 100])

In [91]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [93]:
arr2

array([[777, 777, 777, 777, 777, 777, 777, 777, 777, 777],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [101]:
arr2[8] = 999

In [102]:
arr2

array([[777, 777, 777, 777, 777, 777, 777, 777, 777, 777],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [107]:
arr_2d = np.zeros((10, 10))
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [108]:
arr_2d.shape

(10, 10)

In [109]:
arr_2d.argmin()

0

In [114]:
arr2[[2, 3, 3, 4]]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [115]:
np.zeros((3, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [116]:
arr2

array([[777, 777, 777, 777, 777, 777, 777, 777, 777, 777],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [117]:
arr2[arr2 > 73]

array([777, 777, 777, 777, 777, 777, 777, 777, 777, 777,  74,  75,  76,
        77,  78,  79, 999, 999, 999, 999, 999, 999, 999, 999, 999, 999,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99])

In [118]:
arr2 > 73

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [119]:
np.linspace(0, 1000, 10)

array([    0.        ,   111.11111111,   222.22222222,   333.33333333,
         444.44444444,   555.55555556,   666.66666667,   777.77777778,
         888.88888889,  1000.        ])

In [137]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [138]:
arr_2d[1:4, 0:2]

array([[10, 11],
       [20, 21],
       [30, 31]])

In [140]:
arr_2d[3:, 2:4]

array([[32, 33],
       [42, 43]])

In [143]:
np.random.randn(10, 10)

array([[ 0.04015848, -0.24014084, -0.39798711, -1.04609079, -1.51302934,
         0.547566  , -0.6008921 ,  0.13677508, -0.14619028,  0.30630686],
       [ 0.72916598,  1.43601235,  0.55062955,  1.35502506, -0.24071671,
         1.43185245,  0.95286767,  1.49814114,  0.90461569, -1.12715065],
       [-0.70959244,  0.10696539,  1.19803851,  1.63633172, -0.21606788,
        -1.37947848,  2.33278181, -1.01349698,  0.76655673,  0.59664391],
       [-0.05307474, -0.02662131, -0.02476159, -0.85169954,  0.87627288,
         0.35176695,  0.38068473, -0.20507809,  0.38224593,  0.76704092],
       [-0.9648239 ,  0.44962103,  0.66070966, -0.91180476,  1.02200714,
         0.77264865,  0.94859136, -0.34127304,  0.6802445 ,  0.73496163],
       [-1.05802724, -1.40654995, -0.62021563,  0.67969497,  1.46580956,
        -1.00158382,  1.21320715, -0.04194164, -0.08717351, -1.13806875],
       [-0.89835864,  0.90853168, -0.25219009,  0.84364774,  1.19384674,
         0.46759527,  0.39232894, -0.29088618

In [144]:
arr_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [145]:
arr_2d + arr_2d

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [146]:
arr_2d + 2

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [147]:
arr_2d * 2

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [148]:
np.sqrt(2)

1.4142135623730951

In [149]:
np.exp(2)

7.3890560989306504

In [150]:
np.max(arr_2d)

49

In [151]:
np.sin(arr_2d)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
         0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
        -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388],
       [-0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
        -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539],
       [ 0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
         0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265]])

In [152]:
np.log(4)

1.3862943611198906

In [153]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [154]:
arr.reshape(2, 5)

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9]])

In [155]:
arr.dtype

dtype('int64')

In [157]:
np.ones((10, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [158]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [164]:
np.random.randint(10, 100, (2, 2))

array([[16, 72],
       [26, 22]])

In [167]:
np.random.rand(10, 10)

array([[ 0.89263737,  0.47361178,  0.09125725,  0.84121472,  0.85388861,
         0.64519405,  0.86058822,  0.84862414,  0.32313901,  0.04457881],
       [ 0.22986119,  0.67488204,  0.09501408,  0.19395956,  0.48668063,
         0.88403026,  0.41014201,  0.46886347,  0.2616729 ,  0.52163676],
       [ 0.27202373,  0.33720152,  0.70975345,  0.90609959,  0.54218467,
         0.45130709,  0.93044037,  0.05469737,  0.5943318 ,  0.79698983],
       [ 0.94638319,  0.04259561,  0.57673297,  0.7068228 ,  0.23116957,
         0.6267647 ,  0.71043575,  0.96270455,  0.09608692,  0.32545776],
       [ 0.56223894,  0.95211303,  0.04258054,  0.77425047,  0.78185273,
         0.31746709,  0.60492731,  0.45910395,  0.87401016,  0.5422928 ],
       [ 0.12216633,  0.55696934,  0.14802117,  0.73893766,  0.95194163,
         0.0780066 ,  0.27009672,  0.02142832,  0.30633752,  0.49057725],
       [ 0.96246098,  0.9885882 ,  0.07161945,  0.86016935,  0.4152545 ,
         0.16441055,  0.59527268,  0.18357717