In [1]:
outside = ["G1", "G1", "G1", "G2", "G2", "G2"]
inside = [1, 2, 3, 1, 2, 3]
hier_index = list(zip(outside, inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [3]:
import pandas as pd

In [4]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [5]:
outside = ["A", "A", "A", "B", "B", "B"]
inside = [1, 2, 3, 1, 2, 3]
hier_index = list(zip(outside, inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex(levels=[['A', 'B'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [7]:
import numpy as np

pd.DataFrame(np.random.rand(6, 2), index=hier_index, columns=["A", "B"])

A         B
A 1  0.860792  0.064948
  2  0.975604  0.381659
  3  0.360710  0.697070
B 1  0.696117  0.697751
  2  0.856253  0.185117
  3  0.563646  0.826245

In [8]:
hier_index = list(zip(["A", "A", "A", "B", "B", "B"], [1, 2, 3, 1, 2, 3]))
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex(levels=[['A', 'B'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [11]:
df = pd.DataFrame(np.random.rand(6, 2), index=hier_index, columns=["X", "Y"])

In [12]:
df

X         Y
A 1  0.133253  0.972275
  2  0.998355  0.223726
  3  0.105610  0.717106
B 1  0.294661  0.645476
  2  0.806107  0.511982
  3  0.081566  0.253723

In [14]:
df.loc["A"].loc[1]

X    0.133253
Y    0.972275
Name: 1, dtype: float64

In [16]:
df.index.names

FrozenList([None, None])

In [17]:
df.index.names = ["Group", "No."]

In [18]:
df

X         Y
Group No.                    
A     1    0.133253  0.972275
      2    0.998355  0.223726
      3    0.105610  0.717106
B     1    0.294661  0.645476
      2    0.806107  0.511982
      3    0.081566  0.253723

In [20]:
df.loc["B"].loc[2]['Y']

0.51198229355167624

In [26]:
df2 = pd.DataFrame([[1, 2, np.nan], [3, np.nan, 5]], columns=["A", "B", "C"])
df2

A    B    C
0  1  2.0  NaN
1  3  NaN  5.0

In [25]:
df3 = pd.DataFrame({"A": [1, 2, np.nan],
                    "B": [5, np.nan, np.nan],
                    "C": [1, 2, 3]})

df3

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [29]:
len(np.arange(10))

10

In [34]:
a = np.arange(0, 6) + np.arange(0, 51, 10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [35]:
a[3:, [0, 2, 5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [36]:
!cat pwd

cat: pwd: No such file or directory


In [48]:
np.random.shuffle(a)
a.sort(axis=0)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [51]:
np.may_share_memory(a, a[[2, 3]])

False

In [54]:
np.insert(np.diag([2, 3, 4, 5, 6]), 0, 0, 0)

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [55]:
np.zeros((2, 2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [57]:
help(np.zeros)

Help on built-in function zeros in module numpy.core.multiarray:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    ones_like : Return an array of ones with shape and type of input.
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting v

In [58]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [59]:
np.allclose(a, a)

True

In [60]:
np.array_equal(a, a)

True

In [63]:
np.may_share_memory(a, a.flatten())

False

In [65]:
a.mean(axis=1)

array([  2.5,  12.5,  22.5,  32.5,  42.5,  52.5])

In [72]:
b = np.array([[3, 7, 2], [8, 1, 3]])
b

array([[3, 7, 2],
       [8, 1, 3]])

In [70]:
b.sort(axis=0)
b

array([[1, 3, 7],
       [2, 3, 8]])

In [71]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [76]:
np.sort(b.ravel()).reshape((2, 3))

array([[1, 2, 3],
       [3, 7, 8]])

In [77]:
a[0, 3:5]

array([3, 4])

In [78]:
np.array([1, 0, 1], dtype=bool)

array([ True, False,  True], dtype=bool)

In [79]:
np.median(a, axis=1)

array([  2.5,  12.5,  22.5,  32.5,  42.5,  52.5])

In [80]:
np.sort(b, axis=1)

array([[2, 3, 7],
       [1, 3, 8]])

In [91]:
c = np.array([4, 3, 1, 2])


In [93]:
cc = np.argsort(c)
cc

array([2, 3, 1, 0])

In [94]:
c

array([4, 3, 1, 2])

In [95]:
c[cc]

array([1, 2, 3, 4])

In [96]:
np.random.shuffle(c)

In [97]:
c

array([1, 3, 4, 2])

In [98]:
np.zeros((2, 2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [99]:
c

array([1, 3, 4, 2])

In [100]:
c.sort()

In [101]:
c

array([1, 2, 3, 4])

In [102]:
np.allclose(a, a)

True

In [103]:
np.array_equal(a, a)

True

In [104]:
np.sort(a, axis=1)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [117]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [118]:
a.sum()

45

In [119]:
a.sum(axis=1) # sum rows!

array([ 6, 15, 24])

In [120]:
a.sum(axis=0) # sum columns!

array([12, 15, 18])

In [113]:
df = pd.DataFrame(data=a)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [116]:
df.sum(axis=1) # sum rows!c = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))

0     6
1    15
2    24
dtype: int64

In [121]:
df.sum(axis=0) # sum columns!

0    12
1    15
2    18
dtype: int64

In [123]:
c = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
c

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [124]:
c[2]

array([35, 40, 45])

In [125]:
np.random.randn(2, 2)

array([[ 0.56406308, -0.25750935],
       [-1.8167599 ,  1.60081146]])

In [126]:
np.arange(0, 50).reshape((5, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [127]:
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [128]:
np.linspace(0.01, 1, 100)

array([ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,
        0.1 ,  0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,
        0.19,  0.2 ,  0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,
        0.28,  0.29,  0.3 ,  0.31,  0.32,  0.33,  0.34,  0.35,  0.36,
        0.37,  0.38,  0.39,  0.4 ,  0.41,  0.42,  0.43,  0.44,  0.45,
        0.46,  0.47,  0.48,  0.49,  0.5 ,  0.51,  0.52,  0.53,  0.54,
        0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ,  0.61,  0.62,  0.63,
        0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ,  0.71,  0.72,
        0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ,  0.81,
        0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ,
        0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ])

In [135]:
np.arange(0.01, 1.01, 0.01).reshape((10, 10))

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])