In [2]:
import numpy as np

a = np.array([[3, 7, 2], [8, 1, 3]])

In [5]:
np.sort(a.ravel()).reshape((2, 3))

array([[1, 2, 3],
       [3, 7, 8]])

In [11]:
a = np.arange(1, 5)[::-1].reshape((2, 2))
np.tile(a, (2, 3))

array([[4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1]])

In [15]:
np.may_share_memory(a, a.flatten())

False

In [16]:
mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])

In [18]:
abs(mileposts - mileposts[:, np.newaxis])

array([[   0,  198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448],
       [ 198,    0,  105,  538,  673,  977, 1277, 1346, 1715, 2250],
       [ 303,  105,    0,  433,  568,  872, 1172, 1241, 1610, 2145],
       [ 736,  538,  433,    0,  135,  439,  739,  808, 1177, 1712],
       [ 871,  673,  568,  135,    0,  304,  604,  673, 1042, 1577],
       [1175,  977,  872,  439,  304,    0,  300,  369,  738, 1273],
       [1475, 1277, 1172,  739,  604,  300,    0,   69,  438,  973],
       [1544, 1346, 1241,  808,  673,  369,   69,    0,  369,  904],
       [1913, 1715, 1610, 1177, 1042,  738,  438,  369,    0,  535],
       [2448, 2250, 2145, 1712, 1577, 1273,  973,  904,  535,    0]])

In [19]:
np.array?


In [23]:
a = np.arange(0, 6) + np.arange(0, 51, 10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [25]:
a[0, 3:5]

array([3, 4])

In [27]:
a.mean(axis=0)

array([ 25.,  26.,  27.,  28.,  29.,  30.])

In [29]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [30]:
a[[[2, 3], [4, 5]]]

array([24, 35])

In [32]:
a[[0, 1, 2, 3, 4], [1, 2, 3, 4, 5]]

array([ 1, 12, 23, 34, 45])

In [35]:
b = np.arange(0, 9).reshape((3, 3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
b.mean(axis=0)

array([ 3.,  4.,  5.])

In [39]:
a[[0, 2, 5], 2]

array([ 2, 22, 52])

In [40]:
a[3:, [0, 2, 5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [41]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [42]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [43]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [44]:
c = np.diag([2, 3, 4, 5, 6])

In [45]:
c

array([[2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [47]:
np.insert(c, 0, 0, axis=0)

array([[0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [50]:
np.linspace(0, 9.9, 100)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9])

In [51]:
np.arange(0, 10, .1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9])

In [53]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [54]:
a = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])


In [55]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [56]:
a[1, 1:4]

array([11, 12, 13])

In [57]:
a[2, 5:8]

array([25, 26, 27])

In [60]:
b = np.arange(1, 26).reshape((5, 5))
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [62]:
b[:3, 1]

array([ 2,  7, 12])

In [63]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [64]:
a[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [65]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
c = np.arange(0, 50).reshape((5, 10))

In [69]:
c[3:, 2:4]

array([[32, 33],
       [42, 43]])

In [70]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [71]:
a[2, 5:8]

array([25, 26, 27])

In [72]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [73]:
np.random.randn(25)

array([ 0.53314942, -1.47050685,  0.33243912, -0.6922212 ,  0.64990326,
        0.83620312,  2.488572  , -0.0615789 , -0.0295251 ,  0.79711764,
       -0.7113198 , -0.20987262, -1.485783  ,  1.15463946,  0.71868077,
       -2.00133674,  0.24577817,  1.18954546, -1.61485383,  0.17131884,
       -0.38326866,  0.52493847,  1.63293924, -0.4874796 ,  0.44786077])

In [75]:
b[3, 4]

20

In [76]:
d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [77]:
d[2]

array([35, 40, 45])

In [78]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [79]:
a[1, 1:4]

array([11, 12, 13])

In [80]:
a[:, 6:7]

array([[ 6],
       [16],
       [26],
       [36],
       [46]])

In [81]:
np.linspace(0, 1, 20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [82]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [83]:
a[1:4, :2]

array([[10, 11],
       [20, 21],
       [30, 31]])

In [85]:
from datetime import datetime
datetime.strptime('2015-01-14', "%Y-%m-%d")

datetime.datetime(2015, 1, 14, 0, 0)