In [2]:
import numpy as np

In [7]:
a = np.arange(0, 9).reshape((3, 3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
a.sum(axis=0)

array([ 9, 12, 15])

In [10]:
np.linspace(0.1, 1, 11)

array([ 0.1 ,  0.19,  0.28,  0.37,  0.46,  0.55,  0.64,  0.73,  0.82,
        0.91,  1.  ])

In [11]:
np.tril(a)

array([[0, 0, 0],
       [3, 4, 0],
       [6, 7, 8]])

In [14]:
a.std(axis=1)

array([ 0.81649658,  0.81649658,  0.81649658])

In [17]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [18]:
2**np.arange(0, 5)

array([ 1,  2,  4,  8, 16])

In [19]:
a.sum(axis=0)

array([ 9, 12, 15])

In [20]:
a.sum(axis=1)

array([ 3, 12, 21])

In [22]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [24]:
c.shape

(2, 2, 1)

In [26]:
c.dims

AttributeError: 'numpy.ndarray' object has no attribute 'dims'

In [31]:
b = np.arange(0, 6) + np.arange(0, 51, 10)[:, np.newaxis]
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [32]:
b[0, 3:5]

array([3, 4])

In [33]:
np.array_equal(a, a)

True

In [34]:
np.allclose(a, a)

True

In [36]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [37]:
b[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [38]:
np.arange(0, 10, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9])

In [40]:
np.arange(1, 100, 2)[::-1]

array([99, 97, 95, 93, 91, 89, 87, 85, 83, 81, 79, 77, 75, 73, 71, 69, 67,
       65, 63, 61, 59, 57, 55, 53, 51, 49, 47, 45, 43, 41, 39, 37, 35, 33,
       31, 29, 27, 25, 23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [42]:
q, w, e = a

In [43]:
q

array([0, 1, 2])

In [45]:
c = a.copy()

In [50]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [51]:
b[4:, 4:]

array([[44, 45],
       [54, 55]])

In [52]:
np.array_equal(a, a)

True

In [53]:
np.allclose(a, a)

True

In [54]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [55]:
b[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [56]:
np.sum(a)

36

In [57]:
a.sum()

36

In [61]:
c[:2] = 0
c

array([[0, 0, 0],
       [0, 0, 0],
       [6, 7, 8]])

In [62]:
b[[0, 1, 2, 3, 4], [1, 2, 3, 4, 5]] 

array([ 1, 12, 23, 34, 45])

In [65]:
np.median(a, axis=0)

array([ 3.,  4.,  5.])

In [66]:
mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])

In [68]:
np.abs(mileposts - mileposts[:, np.newaxis])

array([[   0,  198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448],
       [ 198,    0,  105,  538,  673,  977, 1277, 1346, 1715, 2250],
       [ 303,  105,    0,  433,  568,  872, 1172, 1241, 1610, 2145],
       [ 736,  538,  433,    0,  135,  439,  739,  808, 1177, 1712],
       [ 871,  673,  568,  135,    0,  304,  604,  673, 1042, 1577],
       [1175,  977,  872,  439,  304,    0,  300,  369,  738, 1273],
       [1475, 1277, 1172,  739,  604,  300,    0,   69,  438,  973],
       [1544, 1346, 1241,  808,  673,  369,   69,    0,  369,  904],
       [1913, 1715, 1610, 1177, 1042,  738,  438,  369,    0,  535],
       [2448, 2250, 2145, 1712, 1577, 1273,  973,  904,  535,    0]])

In [70]:
c = a.copy()

In [72]:
c[c > 3] = -1

In [73]:
c

array([[ 0,  1,  2],
       [ 3, -1, -1],
       [-1, -1, -1]])

In [74]:
c = a

In [77]:
c[2] = -1
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [-1, -1, -1]])

In [80]:
np.array([np.arange(1, 10, 2)[::-1], np.arange(0, 10, 2)])

array([[9, 7, 5, 3, 1],
       [0, 2, 4, 6, 8]])

In [82]:
np.arange(10)[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [84]:
d = np.arange(0, 10).reshape((2, 5))

In [ ]:
e = d.reshape()

In [85]:
np.array_equal(a, a)

True

In [88]:
np.allclose(a, a)

True

In [89]:
np.allclose(a, a

SyntaxError: unexpected EOF while parsing (<ipython-input-89-712279d7d205>, line 1)

In [91]:
np.sort(a)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [-1, -1, -1]])

In [92]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [93]:
b[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [94]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [-1, -1, -1]])

In [105]:
c = np.arange(10)

In [107]:
np.random.shuffle(c)
c

array([3, 9, 7, 5, 4, 0, 2, 1, 8, 6])

In [108]:
d = np.argsort(c)
d

array([5, 7, 6, 0, 4, 3, 9, 2, 8, 1])

In [109]:
c[d]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.random.rand(3, 3)

array([[ 0.94277292,  0.48100422,  0.68643163],
       [ 0.27964183,  0.81256193,  0.48951603],
       [ 0.47690671,  0.37242535,  0.84344472]])

In [114]:
np.tile(np.linspace(4, 1, 4).reshape((2, 2)), (2, 3))

array([[ 4.,  3.,  4.,  3.,  4.,  3.],
       [ 2.,  1.,  2.,  1.,  2.,  1.],
       [ 4.,  3.,  4.,  3.,  4.,  3.],
       [ 2.,  1.,  2.,  1.,  2.,  1.]])

In [115]:
a.ndim

2

In [117]:
a.shape

(3, 3)

In [118]:
len(a)

3

In [119]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [120]:
b[0, 3:5]

array([3, 4])

In [130]:
e = np.array([[0] * 3, [10] * 3, [20] * 3, [30] * 3])

In [131]:
e + np.array([0, 1, 2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [133]:
np.may_share_memory(a, a.flatten())

False

In [134]:
np.diag([0, 1, 2, 3])

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [140]:
c[np.argsort(c)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
c[0::2] + c[1::2]

array([12, 12,  4,  3, 14])

In [147]:
np.random.shuffle(b)
b

array([[50, 51, 52, 53, 54, 55],
       [ 0,  1,  2,  3,  4,  5],
       [40, 41, 42, 43, 44, 45],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35]])

In [155]:
b.sort(axis=0)
b[4:, 4:]

array([[44, 45],
       [54, 55]])

In [156]:
c = np.array([[3, 7, 2], [8, 1, 3]])
c

array([[3, 7, 2],
       [8, 1, 3]])

In [162]:
c.sort(axis=0)
c

array([[1, 3, 7],
       [2, 3, 8]])

In [164]:
c = b.copy()

In [165]:
c[2:5, 2:5] = 0
c

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21,  0,  0,  0, 25],
       [30, 31,  0,  0,  0, 35],
       [40, 41,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [166]:
a > a

array([[False, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [170]:
np.insert(np.diag([2., 3., 4., 5., 6.]), 0, 0, axis=0)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 2.,  0.,  0.,  0.,  0.],
       [ 0.,  3.,  0.,  0.,  0.],
       [ 0.,  0.,  4.,  0.,  0.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  0.,  6.]])

In [168]:
c.insert?

Object `c.insert` not found.


In [172]:
b[[0, 2, 5], 2]

array([ 2, 22, 52])

In [178]:
np.may_share_memory(c.flatten(), c)

False

In [179]:
np.arange(0, 100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [180]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [192]:
b[:, 2:3]

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52]])

In [198]:
d = np.arange(0, 10)[:, np.newaxis]

In [202]:
len(b)

6

In [203]:
np.arange(0, 6) + np.arange(0, 51, 10)[:, np.newaxis]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [205]:
np.ones((4, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [206]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [209]:
b[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [210]:
e = np.array([[3, 7, 2], [8, 1, 3]])


In [214]:
np.sort(e.ravel()).reshape((2, 3))

array([[1, 2, 3],
       [3, 7, 8]])

In [216]:
np.tile(np.arange(4), (4, 1))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [218]:
d = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [220]:
d[1, 1:4]

array([11, 12, 13])

In [221]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [223]:
np.arange(0, 50).reshape((5, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [226]:
d[:, 6]

array([ 6, 16, 26, 36, 46])

In [227]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [229]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21,  0,  0,  0, 25],
       [30, 31,  0,  0,  0, 35],
       [40, 41,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [231]:
e = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [234]:
e[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [236]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [238]:
d.dtype

dtype('int64')

In [239]:
np.linspace(0, 10, 100)

array([  0.        ,   0.1010101 ,   0.2020202 ,   0.3030303 ,
         0.4040404 ,   0.50505051,   0.60606061,   0.70707071,
         0.80808081,   0.90909091,   1.01010101,   1.11111111,
         1.21212121,   1.31313131,   1.41414141,   1.51515152,
         1.61616162,   1.71717172,   1.81818182,   1.91919192,
         2.02020202,   2.12121212,   2.22222222,   2.32323232,
         2.42424242,   2.52525253,   2.62626263,   2.72727273,
         2.82828283,   2.92929293,   3.03030303,   3.13131313,
         3.23232323,   3.33333333,   3.43434343,   3.53535354,
         3.63636364,   3.73737374,   3.83838384,   3.93939394,
         4.04040404,   4.14141414,   4.24242424,   4.34343434,
         4.44444444,   4.54545455,   4.64646465,   4.74747475,
         4.84848485,   4.94949495,   5.05050505,   5.15151515,
         5.25252525,   5.35353535,   5.45454545,   5.55555556,
         5.65656566,   5.75757576,   5.85858586,   5.95959596,
         6.06060606,   6.16161616,   6.26262626,   6.36

In [242]:
d[2, 5:8]

array([25, 26, 27])

In [244]:
d[1, 1:4]

array([11, 12, 13])

In [247]:
d[1:4, 0:2]

array([[10, 11],
       [20, 21],
       [30, 31]])

In [248]:
d[3:, 2:4]

array([[32, 33],
       [42, 43]])

In [249]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [251]:
np.random.rand(2, 2)

array([[ 0.69642788,  0.09522647],
       [ 0.54499475,  0.38075465]])

In [253]:
np.linspace(0, 1, 20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [254]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [258]:
e[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [264]:
np.random.randint(2, 10, (2, 2))

array([[7, 3],
       [9, 6]])

In [269]:
e[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [270]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [271]:
d[2, 5:8]

array([25, 26, 27])

In [ ]:
np.array()

In [272]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [274]:
a.sum(axis=1)

array([ 6, 15, 24])

In [1]:
top = ["G1", "G1", "G1", "G2", "G2", "G2"]
lower = [1, 2, 3, 1, 2, 3]
hier_index = list(zip(top, lower))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [2]:
import pandas as pd
import numpy as np

In [6]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [8]:
df = pd.DataFrame(data=np.random.rand(6, 2), index=hier_index, columns=["A", "B"])
df

A         B
G1 1  0.399792  0.753887
   2  0.924003  0.757745
   3  0.958928  0.429121
G2 1  0.095662  0.858786
   2  0.541100  0.536351
   3  0.139584  0.466476

In [11]:
df.loc["G1"].loc[1]['A']

0.39979178352500755

In [15]:
df.index.names = ["Group", "No."]
df

A         B
Group No.                    
G1    1    0.399792  0.753887
      2    0.924003  0.757745
      3    0.958928  0.429121
G2    1    0.095662  0.858786
      2    0.541100  0.536351
      3    0.139584  0.466476

In [16]:
df.loc["G2"].loc[3]["B"]

0.46647594431391592

In [23]:
df2 = pd.DataFrame(data=[[1, 2, 3], [4, 5, 6]], columns=["A", "B", "C"])
df2

A  B  C
0  1  2  3
1  4  5  6

In [26]:
df2.sum(axis=0)

A    5
B    7
C    9
dtype: int64

In [27]:
df2.sum(axis=1)

0     6
1    15
dtype: int64

In [29]:
df3 = pd.DataFrame(data=[[1, 2, np.nan], [3, np.nan, 4]])
df3

0    1    2
0  1  2.0  NaN
1  3  NaN  4.0

In [30]:
df3.dropna()

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [32]:
df3.dropna(axis=0)

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [33]:
df3.dropna(axis=1)

0
0  1
1  3

In [34]:
df3.dropna(axis=0)

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [35]:
pd.DataFrame(data=[[1, 2, 3], [4, 5, 6]], index=["a", "b"], columns=["A", "B", "C"])

A  B  C
a  1  2  3
b  4  5  6

In [36]:
df3

0    1    2
0  1  2.0  NaN
1  3  NaN  4.0

In [38]:
df3.dropna(axis=1)

0
0  1
1  3

In [40]:
df4 = pd.DataFrame(data=np.random.rand(5, 4), index=["A", "B", "C", "D", "E"], columns=["W", "X", "Y", "Z"])
df4

W         X         Y         Z
A  0.476433  0.064033  0.151388  0.225450
B  0.654328  0.714566  0.301302  0.011050
C  0.966447  0.823579  0.322833  0.363199
D  0.523553  0.031796  0.879537  0.547335
E  0.387970  0.411835  0.286662  0.330025

In [43]:
df4[df4 > .5]

W         X         Y         Z
A       NaN       NaN       NaN       NaN
B  0.654328  0.714566       NaN       NaN
C  0.966447  0.823579       NaN       NaN
D  0.523553       NaN  0.879537  0.547335
E       NaN       NaN       NaN       NaN

In [45]:
df4[df4["W"] > .5]["Y"]

B    0.301302
C    0.322833
D    0.879537
Name: Y, dtype: float64

In [49]:
df3.dropna(axis=0, thresh=1)

0    1    2
0  1  2.0  NaN
1  3  NaN  4.0

In [56]:
df3

0    1    2
0  1  2.0  NaN
1  3  NaN  4.0

In [57]:
df3.fillna("a")

0  1  2
0  1  2  a
1  3  a  4

In [60]:
df2.A

0    1
1    4
Name: A, dtype: int64

In [67]:
df3[1].fillna(df3[1].mean())

0    2.0
1    2.0
Name: 1, dtype: float64

In [68]:
pd.DataFrame(data={"A": [1, 2, 3],
                   "B": [3, 4, 5],
                   "C": [6, 7, 8]})

A  B  C
0  1  3  6
1  2  4  7
2  3  5  8

In [71]:
df4[df4 > 2]

W   X   Y   Z
A NaN NaN NaN NaN
B NaN NaN NaN NaN
C NaN NaN NaN NaN
D NaN NaN NaN NaN
E NaN NaN NaN NaN

In [72]:
data = {"Company": ["GOOG", "GOOG", "MSFT", "MSFT", "FB", "FB"],
        "Person": ["Sam", "Charlie", "Amy", "Vanessa", "Carl", "Sarah"],
        "Sales": [200, 120, 340, 124, 243, 350]}
df5 = pd.DataFrame(data)
df5


Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [76]:
df5_grouped = df5.groupby("Company")

In [80]:
df5_grouped.describe().transpose()

Company    FB                                                         GOOG  \
        count   mean        std    min     25%    50%     75%    max count   
Sales     2.0  296.5  75.660426  243.0  269.75  296.5  323.25  350.0   2.0   

Company         ...                  MSFT                                   \
          mean  ...      75%    max count   mean         std    min    25%   
Sales    160.0  ...    180.0  200.0   2.0  232.0  152.735065  124.0  178.0   

Company                       
           50%    75%    max  
Sales    232.0  286.0  340.0  

[1 rows x 24 columns]

In [81]:
pd.Series(data={"A": 1, "B": 2})


A    1
B    2
dtype: int64

In [82]:
df5.groupby("Company").mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [85]:
df3.dropna(axis=0, thresh=1)

0    1    2
0  1  2.0  NaN
1  3  NaN  4.0

In [86]:
df3.fillna("-1")

0   1   2
0  1   2  -1
1  3  -1   4

In [89]:
df3[1].fillna(value=df3[1].mean())

0    2.0
1    2.0
Name: 1, dtype: float64

In [92]:
df5.groupby("Company").sum().loc["FB"]

Sales    593
Name: FB, dtype: int64

In [96]:
df2

A  B  C
0  1  2  3
1  4  5  6

In [98]:
df2.drop(0, axis=0)

A  B  C
1  4  5  6

In [99]:
df2.drop("A", axis=1)

B  C
0  2  3
1  5  6

In [100]:
df2[["A", "B"]]

A  B
0  1  2
1  4  5

In [101]:
df5

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [103]:
np.random.seed(101)
df6 = pd.DataFrame(np.random.randn(5, 4), index=["A", "B", "C", "D", "E"], columns=["W", "X", "Y", "Z"])
df6

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [104]:
df6["idx"] = [1, 2, 3, 4, 5]
df6

W         X         Y         Z  idx
A  2.706850  0.628133  0.907969  0.503826    1
B  0.651118 -0.319318 -0.848077  0.605965    2
C -2.018168  0.740122  0.528813 -0.589001    3
D  0.188695 -0.758872 -0.933237  0.955057    4
E  0.190794  1.978757  2.605967  0.683509    5

In [105]:
df6.set_index("idx")

W         X         Y         Z
idx                                        
1    2.706850  0.628133  0.907969  0.503826
2    0.651118 -0.319318 -0.848077  0.605965
3   -2.018168  0.740122  0.528813 -0.589001
4    0.188695 -0.758872 -0.933237  0.955057
5    0.190794  1.978757  2.605967  0.683509

In [109]:
df6.drop("idx", axis=1)
df6.loc["B"]

W      0.651118
X     -0.319318
Y     -0.848077
Z      0.605965
idx    2.000000
Name: B, dtype: float64

In [113]:
df6[df6["W"] > 0]

W         X         Y         Z  idx
A  2.706850  0.628133  0.907969  0.503826    1
B  0.651118 -0.319318 -0.848077  0.605965    2
D  0.188695 -0.758872 -0.933237  0.955057    4
E  0.190794  1.978757  2.605967  0.683509    5

In [116]:
df5.groupby("Company").describe()

Sales
Company                  
FB      count    2.000000
        mean   296.500000
        std     75.660426
        min    243.000000
        25%    269.750000
        50%    296.500000
        75%    323.250000
        max    350.000000
GOOG    count    2.000000
        mean   160.000000
        std     56.568542
        min    120.000000
        25%    140.000000
        50%    160.000000
        75%    180.000000
        max    200.000000
MSFT    count    2.000000
        mean   232.000000
        std    152.735065
        min    124.000000
        25%    178.000000
        50%    232.000000
        75%    286.000000
        max    340.000000

In [119]:
df6.reset_index(drop=True)

W         X         Y         Z  idx
0  2.706850  0.628133  0.907969  0.503826    1
1  0.651118 -0.319318 -0.848077  0.605965    2
2 -2.018168  0.740122  0.528813 -0.589001    3
3  0.188695 -0.758872 -0.933237  0.955057    4
4  0.190794  1.978757  2.605967  0.683509    5

In [122]:
df6[(df6["W"] > 0) & (df6["Y"] < 0)]

W         X         Y         Z  idx
B  0.651118 -0.319318 -0.848077  0.605965    2
D  0.188695 -0.758872 -0.933237  0.955057    4

In [123]:
df10 = pd.DataFrame({"A": ["A0", "A1", "A2", "A3"],
                    "B": ["B0", "B1", "B2", "B3"],
                    "C": ["C0", "C1", "C2", "C3"],
                    "D": ["D0", "D1", "D2", "D3"]},
                  index=[0, 1, 2, 3])

In [125]:
df11 = pd.DataFrame({"A": ["A4", "A5", "A6", "A7"],
                    "B": ["B4", "B5", "B6", "B7"],
                    "C": ["C4", "C5", "C6", "C7"],
                    "D": ["D4", "D5", "D6", "D7"]},
                  index=[4, 5, 6, 7])

In [126]:
df10

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [127]:
df11

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [130]:
pd.concat([df10, df11])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [135]:
df4

W         X         Y         Z
A  0.476433  0.064033  0.151388  0.225450
B  0.654328  0.714566  0.301302  0.011050
C  0.966447  0.823579  0.322833  0.363199
D  0.523553  0.031796  0.879537  0.547335
E  0.387970  0.411835  0.286662  0.330025

In [136]:
df4.iloc[1]

W    0.654328
X    0.714566
Y    0.301302
Z    0.011050
Name: B, dtype: float64

In [138]:
pd.concat([df10, df11], axis=1)

A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [139]:

left = pd.DataFrame({"key": ["K0", "K1", "K2", "K3"],
                     "A": ["A0", "A1", "A2", "A3"],
                     "B": ["B0", "B1", "B2", "B3"]})
left

A   B key
0  A0  B0  K0
1  A1  B1  K1
2  A2  B2  K2
3  A3  B3  K3

In [141]:
right = pd.DataFrame({"key": ["K0", "K1", "K2", "K3"],
                      "C": ["C0", "C1", "C2", "C3"],
                      "D": ["D0", "D1", "D2", "D3"]})
right

C   D key
0  C0  D0  K0
1  C1  D1  K1
2  C2  D2  K2
3  C3  D3  K3

In [143]:
pd.merge(left, right, on="key")

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

In [144]:
df3

0    1    2
0  1  2.0  NaN
1  3  NaN  4.0

In [145]:
df4

W         X         Y         Z
A  0.476433  0.064033  0.151388  0.225450
B  0.654328  0.714566  0.301302  0.011050
C  0.966447  0.823579  0.322833  0.363199
D  0.523553  0.031796  0.879537  0.547335
E  0.387970  0.411835  0.286662  0.330025

In [147]:
df4.loc["A", "X"]

0.064033205725241404

In [158]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

pd.merge(left, right, on=["key1", "key2"], how="inner")

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

In [149]:
left


A   B key1 key2
0  A0  B0   K0   K0
1  A1  B1   K0   K1
2  A2  B2   K1   K0
3  A3  B3   K2   K1

In [150]:
right

C   D key1 key2
0  C0  D0   K0   K0
1  C1  D1   K1   K0
2  C2  D2   K1   K0
3  C3  D3   K2   K0

In [151]:
pd.merge(left, right, on=["key1", "key2"], how="inner")

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

In [152]:
pd.merge(left, right, on=["key1", "key2"], how="outer")

A    B key1 key2    C    D
0   A0   B0   K0   K0   C0   D0
1   A1   B1   K0   K1  NaN  NaN
2   A2   B2   K1   K0   C1   D1
3   A2   B2   K1   K0   C2   D2
4   A3   B3   K2   K1  NaN  NaN
5  NaN  NaN   K2   K0   C3   D3

In [155]:
pd.concat([df10, df11], axis=1)

A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [160]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [161]:
pd.merge(left, right, how="right", on=["key1", "key2"])

A    B key1 key2   C   D
0   A0   B0   K0   K0  C0  D0
1   A2   B2   K1   K0  C1  D1
2   A2   B2   K1   K0  C2  D2
3  NaN  NaN   K2   K0  C3  D3

In [162]:
pd.merge(left, right, how="left", on=["key1", "key2"])

A   B key1 key2    C    D
0  A0  B0   K0   K0   C0   D0
1  A1  B1   K0   K1  NaN  NaN
2  A2  B2   K1   K0   C1   D1
3  A2  B2   K1   K0   C2   D2
4  A3  B3   K2   K1  NaN  NaN

In [167]:
df4.loc["A", "X"]

0.064033205725241404

In [168]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])


In [170]:
left.join(right, how="left")

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [173]:
df4


W         X         Y         Z
A  0.476433  0.064033  0.151388  0.225450
B  0.654328  0.714566  0.301302  0.011050
C  0.966447  0.823579  0.322833  0.363199
D  0.523553  0.031796  0.879537  0.547335
E  0.387970  0.411835  0.286662  0.330025

In [174]:
df4.drop("B")

W         X         Y         Z
A  0.476433  0.064033  0.151388  0.225450
C  0.966447  0.823579  0.322833  0.363199
D  0.523553  0.031796  0.879537  0.547335
E  0.387970  0.411835  0.286662  0.330025

In [175]:
pd.DataFrame(data=np.random.rand(3, 4), index=["a", "b", "c"], columns=["A", "B", "C", "D"])

A         B         C         D
a  0.734819  0.541962  0.913154  0.807920
b  0.402998  0.357224  0.952877  0.343632
c  0.865100  0.830278  0.538161  0.922469

In [177]:
df4.tail()

W         X         Y         Z
A  0.476433  0.064033  0.151388  0.225450
B  0.654328  0.714566  0.301302  0.011050
C  0.966447  0.823579  0.322833  0.363199
D  0.523553  0.031796  0.879537  0.547335
E  0.387970  0.411835  0.286662  0.330025

In [178]:
df4["W"].unique()

array([ 0.47643337,  0.65432788,  0.96644718,  0.52355276,  0.3879696 ])

In [181]:
df4["W"].nunique()

5

In [184]:
df4["W"].value_counts()

0.966447    1
0.523553    1
0.387970    1
0.476433    1
0.654328    1
Name: W, dtype: int64

In [185]:
df4[(df4["W"] > 4) | (df4["Y"] < 1)]

W         X         Y         Z
A  0.476433  0.064033  0.151388  0.225450
B  0.654328  0.714566  0.301302  0.011050
C  0.966447  0.823579  0.322833  0.363199
D  0.523553  0.031796  0.879537  0.547335
E  0.387970  0.411835  0.286662  0.330025

In [186]:
pd.Series(data=[1, 2, 3, 4], index=["Poland", "usa", "germany", "russia"])

Poland     1
usa        2
germany    3
russia     4
dtype: int64

In [187]:
pd.Series(data=np.arange(10))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [189]:
df4.apply(lambda x: x**2)

W         X         Y         Z
A  0.226989  0.004100  0.022918  0.050828
B  0.428145  0.510604  0.090783  0.000122
C  0.934020  0.678282  0.104221  0.131914
D  0.274107  0.001011  0.773585  0.299575
E  0.150520  0.169608  0.082175  0.108917

In [190]:
pd.Series(data=[1, 2, 3], index=["a", "b", "c"])

a    1
b    2
c    3
dtype: int64

In [191]:
df4["W"].sum()

3.0087307900326206

In [192]:
df4.drop("W", axis=1)

X         Y         Z
A  0.064033  0.151388  0.225450
B  0.714566  0.301302  0.011050
C  0.823579  0.322833  0.363199
D  0.031796  0.879537  0.547335
E  0.411835  0.286662  0.330025

In [193]:
df4.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [194]:
df4.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [197]:
df4.sort_values(by="W")

W         X         Y         Z
E  0.387970  0.411835  0.286662  0.330025
A  0.476433  0.064033  0.151388  0.225450
D  0.523553  0.031796  0.879537  0.547335
B  0.654328  0.714566  0.301302  0.011050
C  0.966447  0.823579  0.322833  0.363199

In [201]:
df4['W'].value_counts()

0.966447    1
0.523553    1
0.387970    1
0.476433    1
0.654328    1
Name: W, dtype: int64

In [ ]:
df.apply()

In [203]:
df4.drop("W", axis=1)

X         Y         Z
A  0.064033  0.151388  0.225450
B  0.714566  0.301302  0.011050
C  0.823579  0.322833  0.363199
D  0.031796  0.879537  0.547335
E  0.411835  0.286662  0.330025

In [204]:
df4["W"].sum()

3.0087307900326206

In [207]:
df4.columns = ["A", "B", "C", "D"]

In [206]:
df4.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [208]:
df4

A         B         C         D
A  0.476433  0.064033  0.151388  0.225450
B  0.654328  0.714566  0.301302  0.011050
C  0.966447  0.823579  0.322833  0.363199
D  0.523553  0.031796  0.879537  0.547335
E  0.387970  0.411835  0.286662  0.330025

In [209]:
df4.sort_values(by="A")

A         B         C         D
E  0.387970  0.411835  0.286662  0.330025
A  0.476433  0.064033  0.151388  0.225450
D  0.523553  0.031796  0.879537  0.547335
B  0.654328  0.714566  0.301302  0.011050
C  0.966447  0.823579  0.322833  0.363199

In [210]:
df4.isnull()

A      B      C      D
A  False  False  False  False
B  False  False  False  False
C  False  False  False  False
D  False  False  False  False
E  False  False  False  False

In [212]:
df3.dropna()

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [219]:
df4.sort_values(by="A")

A         B         C         D
E  0.387970  0.411835  0.286662  0.330025
A  0.476433  0.064033  0.151388  0.225450
D  0.523553  0.031796  0.879537  0.547335
B  0.654328  0.714566  0.301302  0.011050
C  0.966447  0.823579  0.322833  0.363199

In [216]:
!ls data

populations.txt


In [221]:
df4.to_csv("test.csv")

In [222]:
!ls

1.3.1_the_numpy_array_object.ipynb
1.3.2_numerical_operations_on_arrays.ipynb
data
sandbox.ipynb
test.csv


In [223]:
df4.to_excel("test.xls")

In [224]:
pd.DataFrame(data=[[1, 2.0, np.nan], [3, np.nan, 5.0]], columns=["A", "B", "C"])

A    B    C
0  1  2.0  NaN
1  3  NaN  5.0

In [225]:
pd.DataFrame(data={"A": [1.0, 2.0, np.nan], "B": [5.0, np.nan, np.nan], "C": [1, 2, 3]})

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [228]:
df2

A  B  C
0  1  2  3
1  4  5  6

In [234]:
df2.sum(axis=1)

0     6
1    15
dtype: int64

In [235]:
c = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))

In [236]:
c

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [237]:
c[0:2, 1:]

array([[10, 15],
       [25, 30]])

In [239]:
a = np.arange(0, 50).reshape((5, 10))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [242]:
a[3:, 2:4]

array([[32, 33],
       [42, 43]])

In [244]:
d = np.linspace(0, 1, 20)

In [245]:
d.sum()

10.0

In [246]:
d.std()

0.30348848933344197

In [248]:
d.sum(axis=0)

10.0

In [252]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [254]:
a[:, 6:7]

array([[ 6],
       [16],
       [26],
       [36],
       [46]])

In [259]:
b = np.arange(1, 26).reshape((5, 5))
b


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [261]:
b[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [264]:
%timeit b[4]

The slowest run took 27.39 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 219 ns per loop


In [266]:
df = pd.DataFrame([[0, 1, 2,], [3, 4, 5]])
df

0  1  2
0  0  1  2
1  3  4  5

In [268]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [269]:
df.sum(axis=1)

0     3
1    12
dtype: int64

In [270]:
a.sum(axis=1)

array([ 3, 12])

In [274]:
d > 0.5

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [278]:
a = np.arange(0, 9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [286]:
np.random.shuffle(a)
a

array([6, 1, 7, 2, 5, 8, 3, 4, 0])

In [287]:
aa = a.reshape((3, 3))

In [288]:
np.may_share_memory(a, aa)

True

In [289]:
a

array([6, 1, 7, 2, 5, 8, 3, 4, 0])

In [290]:
aa

array([[6, 1, 7],
       [2, 5, 8],
       [3, 4, 0]])

In [294]:
np.sort(aa, axis=0)

array([[2, 1, 0],
       [3, 4, 7],
       [6, 5, 8]])

In [285]:
aa

array([[1, 5, 6],
       [0, 2, 8],
       [3, 4, 7]])

In [295]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [296]:
np.array_equal(a ,a)

True

In [297]:
np.allclose(a, a)

True

In [299]:
np.linspace(0, 0.8, 5)

array([ 0. ,  0.2,  0.4,  0.6,  0.8])