# Intro - Analyzing subway and weather data

How ridership changes when it starts raining?

How does it change from summet to winter?

Which stops are most and least popular?

How ridership is affected by some cultural events - identify the biggest changes in regular usage.

Were there some stops in operating of some of the stations?

---

What variables are related to subway ridership?

Which stations have the most riders?

Ridership patterns over time - how it changes during the day and month?

Will memorial day ridership will be similar to weekend day ridership?

How weather affects ridership?



## Two-dimensional Data 
Python: List of lists

NumPy: 2D array

Pandas: DataFrame

2D array, as opposed to array of arrays:
- Memory efficient
- Different elements accesing
`a[1, 3]` rather than `a[1][3]` - row
- mean(), std(). etc. operate on entire array

In [2]:
import numpy as np

# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

# Accessing elements
print(ridership[1, 3])
print(ridership[1:3, 3:5])
print(ridership[1, :])

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


In [3]:
# Vectorized operations on rows or columns
print(ridership[0, :] + ridership[1, :])
print(ridership[:, 0] + ridership[:, 1])

[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [4]:
# Vectorized operations on entire arrays
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print(a + b)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [5]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    max_station_idx = np.argmax(ridership[0, :])
    overall_mean = ridership.mean()
    mean_for_max = ridership[:, max_station_idx].mean()
    
    return (overall_mean, mean_for_max)

mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001)

The max station had much higher mean than the overall stations average.

## Operations along an Axis

Many NumPy functions like mean() opearate on an array as a whole. But in many cases it might make sense to calculate the operation by row or by column.

Most of NumPy function take an axis argument for this reason - 0 or 1
- 0 calculates for each column
- 1 calculates for each row

In [8]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(a.sum())
print(a.sum(axis=0)) # sum rows!
print(a.sum(axis=1)) # sum columns!

45
[12 15 18]
[ 6 15 24]


In [7]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
    '''
    stations_means = ridership.mean(axis=0)
    max_daily_ridership = stations_means.max()    # Replace this with your code
    min_daily_ridership = stations_means.min()     # Replace this with your code
    
    return (max_daily_ridership, min_daily_ridership)

min_and_max_riders_per_day(ridership)

(3239.9000000000001, 1071.2)

Maximal and minimal ridership means for different stations.

Which stations are these?

## NumPy And Pandas Data Types

In [9]:
np.array([1, 2, 3, 4, 5]).dtype

dtype('int64')

It is difficult or impossible to store different types of data - like strings and floats - in array.

The solution is to store the complex data in DataFrame.

## Accessing Elements Of A DataFrame

Use .loc[] to access a single row of a data in DataFrame by indexes (THEIR NAMES!).

Use .iloc[] to access a single row of data in DataFrame by positions (INDEX NUMBER).

To access a single element of a DataFrame you can also use .loc and .iloc but indicating both a row and a column.

You can also access columns using square brackets.

In [13]:
import pandas as pd

# You can create a DataFrame out of a dictionary mapping column names to values
df_1 = pd.DataFrame({"A": [0, 1, 2], "B": [3, 4, 5]})
df_1

A  B
0  0  3
1  1  4
2  2  5

In [14]:
# You can also use a list of lists or a 2D NumPy array
df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=["A", "B", "C"])
df_2

A  B  C
0  0  1  2
1  3  4  5

In [15]:
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)
ridership_df

R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
05-05-11  1608  4802  3932  4477  2705
05-06-11  1576  3933  3909  4979  2685
05-07-11    95   229   255   496   201
05-08-11     2     0     1    27     0
05-09-11  1438  3785  3589  4174  2215
05-10-11  1342  4043  4009  4665  3033

In [18]:
# Accessing elements.
print(ridership_df.iloc[0])
print(ridership_df.loc["05-05-11"])
print(ridership_df["R003"])
print(ridership_df.iloc[1, 3])

R003    0
R004    0
R005    2
R006    5
R007    0
Name: 05-01-11, dtype: int64
R003    1608
R004    4802
R005    3932
R006    4477
R007    2705
Name: 05-05-11, dtype: int64
05-01-11       0
05-02-11    1478
05-03-11    1613
05-04-11    1560
05-05-11    1608
05-06-11    1576
05-07-11      95
05-08-11       2
05-09-11    1438
05-10-11    1342
Name: R003, dtype: int64
2328


In [19]:
# Accessing multiple rows
ridership_df.iloc[1:4]

R003  R004  R005  R006  R007
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613

In [20]:
# Accessing multiple columns
ridership_df[["R003", "R005"]]

R003  R005
05-01-11     0     2
05-02-11  1478  3674
05-03-11  1613  3991
05-04-11  1560  3826
05-05-11  1608  3932
05-06-11  1576  3909
05-07-11    95   255
05-08-11     2     1
05-09-11  1438  3589
05-10-11  1342  4009

In [22]:
# Pandas axis
df = pd.DataFrame({"A": [0, 1, 2], "B": [3, 4, 5]})
df

A  B
0  0  3
1  1  4
2  2  5

In [23]:
df.sum()

A     3
B    12
dtype: int64

In [24]:
df.sum(axis=0)

A     3
B    12
dtype: int64

In [25]:
df.sum(axis=1)

0    3
1    5
2    7
dtype: int64

In [26]:
df.values.sum()

15

In [50]:
# Returns not index but column name!
df.iloc[0].argmax() 

'B'

In [47]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    This is the same as a previous exercise, but this time the
    input is a Pandas DataFrame rather than a 2D NumPy array.
    '''
    
    max_station = ridership.iloc[0].argmax()
    
    overall_mean = ridership.values.mean() # Replace this with your code
    mean_for_max = ridership[max_station].mean() # Replace this with your code
    
    return (overall_mean, mean_for_max)

In [48]:
mean_riders_for_max_station(ridership_df)

(2342.5999999999999, 3239.9)

## Loading Data Into A DataFrame

DataFrames are a great data structure to represent CSV!

In [51]:
subway_df = pd.read_csv("nyc_subway_weather.csv")

In [52]:
subway_df.head()

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002              0.0   
1  R003  05-01-11  04:00:00   4388333  2911002              0.0   
2  R003  05-01-11  12:00:00   4388333  2911002              0.0   
3  R003  05-01-11  16:00:00   4388333  2911002              0.0   
4  R003  05-01-11  20:00:00   4388333  2911002              0.0   

   EXITSn_hourly             datetime  hour  day_week     ...       pressurei  \
0            0.0  2011-05-01 00:00:00     0         6     ...           30.22   
1            0.0  2011-05-01 04:00:00     4         6     ...           30.25   
2            0.0  2011-05-01 12:00:00    12         6     ...           30.28   
3            0.0  2011-05-01 16:00:00    16         6     ...           30.26   
4            0.0  2011-05-01 20:00:00    20         6     ...           30.28   

  rain  tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  \
0    0   55.9    3.5         0.0         30.258      55.98       7.86   
1    0   52.0    3.5         0.0         30.258      55.98       7.86   
2    0   62.1    6.9         0.0         30.258      55.98       7.86   
3    0   57.9   15.0         0.0         30.258      55.98       7.86   
4    0   52.0   10.4         0.0         30.258      55.98       7.86   

   weather_lat  weather_lon  
0    40.700348   -73.887177  
1    40.700348   -73.887177  
2    40.700348   -73.887177  
3    40.700348   -73.887177  
4    40.700348   -73.887177  

[5 rows x 27 columns]

In [53]:
subway_df.describe()

ENTRIESn        EXITSn  ENTRIESn_hourly  EXITSn_hourly  \
count  4.264900e+04  4.264900e+04     42649.000000   42649.000000   
mean   2.812486e+07  1.986993e+07      1886.589955    1361.487866   
std    3.043607e+07  2.028986e+07      2952.385585    2183.845409   
min    0.000000e+00  0.000000e+00         0.000000       0.000000   
25%    1.039762e+07  7.613712e+06       274.000000     237.000000   
50%    1.818389e+07  1.331609e+07       905.000000     664.000000   
75%    3.263049e+07  2.393771e+07      2255.000000    1537.000000   
max    2.357746e+08  1.493782e+08     32814.000000   34828.000000   

               hour      day_week       weekday      latitude     longitude  \
count  42649.000000  42649.000000  42649.000000  42649.000000  42649.000000   
mean      10.046754      2.905719      0.714436     40.724647    -73.940364   
std        6.938928      2.079231      0.451688      0.071650      0.059713   
min        0.000000      0.000000      0.000000     40.576152    -74.073622   
25%        4.000000      1.000000      0.000000     40.677107    -73.987342   
50%       12.000000      3.000000      1.000000     40.717241    -73.953459   
75%       16.000000      5.000000      1.000000     40.759123    -73.907733   
max       20.000000      6.000000      1.000000     40.889185    -73.755383   

                fog      ...          pressurei          rain         tempi  \
count  42649.000000      ...       42649.000000  42649.000000  42649.000000   
mean       0.009824      ...          29.971096      0.224741     63.103780   
std        0.098631      ...           0.137942      0.417417      8.455597   
min        0.000000      ...          29.550000      0.000000     46.900000   
25%        0.000000      ...          29.890000      0.000000     57.000000   
50%        0.000000      ...          29.960000      0.000000     61.000000   
75%        0.000000      ...          30.060000      0.000000     69.100000   
max        1.000000      ...          30.320000      1.000000     86.000000   

              wspdi   meanprecipi  meanpressurei     meantempi     meanwspdi  \
count  42649.000000  42649.000000   42649.000000  42649.000000  42649.000000   
mean       6.927872      0.004618      29.971096     63.103780      6.927872   
std        4.510178      0.016344       0.131158      6.939011      3.179832   
min        0.000000      0.000000      29.590000     49.400000      0.000000   
25%        4.600000      0.000000      29.913333     58.283333      4.816667   
50%        6.900000      0.000000      29.958000     60.950000      6.166667   
75%        9.200000      0.000000      30.060000     67.466667      8.850000   
max       23.000000      0.157500      30.293333     79.800000     17.083333   

        weather_lat   weather_lon  
count  42649.000000  42649.000000  
mean      40.728555    -73.938693  
std        0.065420      0.059582  
min       40.600204    -74.014870  
25%       40.688591    -73.985130  
50%       40.720570    -73.949150  
75%       40.755226    -73.912033  
max       40.862064    -73.694176  

[8 rows x 21 columns]

## DataFrame Vectorized Operations

Similar to vectorized operations for 2d NumPy arrays.

Match elements by index and column name rather than position.

In [56]:
# Adding DataFrames with the column names
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({"a": [10, 20, 30], "b": [40, 50, 60], 'c': [70, 80, 90]})

In [57]:
df1

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [58]:
df2

a   b   c
0  10  40  70
1  20  50  80
2  30  60  90

In [59]:
df1 + df2

a   b   c
0  11  44  77
1  22  55  88
2  33  66  99

In [60]:
# Adding DataFrames with overlapping column names
df1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]})
df2 = pd.DataFrame({"d": [10, 20, 30], "c": [40, 50, 60], "b": [70, 80, 90]})

In [61]:
df1

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [62]:
df2

b   c   d
0  70  40  10
1  80  50  20
2  90  60  30

In [63]:
df1 + df2

a   b   c   d
0 NaN  74  47 NaN
1 NaN  85  58 NaN
2 NaN  96  69 NaN

In [64]:
# Adding DataFrames with overlapping row indexes
df1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]},
                  index=["row1", "row2", "row3"])
df2 = pd.DataFrame({"a": [10, 20, 30], "b": [40, 50, 60], "c": [70, 80, 90]},
                  index=["row4", "row3", "row2"])

In [65]:
df1

a  b  c
row1  1  4  7
row2  2  5  8
row3  3  6  9

In [66]:
df2

a   b   c
row4  10  40  70
row3  20  50  80
row2  30  60  90

In [67]:
df1 + df2

a     b     c
row1   NaN   NaN   NaN
row2  32.0  65.0  98.0
row3  23.0  56.0  89.0
row4   NaN   NaN   NaN

## Difference from columns

In [70]:
entries_and_exits = pd.DataFrame({
    'ENTRIES': [3144312, 3144335, 3144353, 3144424, 3144594,
                 3144808, 3144895, 3144905, 3144941, 3145094],
    'EXITS': [1088151, 1088159, 1088177, 1088231, 1088275,
               1088317, 1088328, 1088331, 1088420, 1088753]
})
entries_and_exits

ENTRIES    EXITS
0  3144312  1088151
1  3144335  1088159
2  3144353  1088177
3  3144424  1088231
4  3144594  1088275
5  3144808  1088317
6  3144895  1088328
7  3144905  1088331
8  3144941  1088420
9  3145094  1088753

In [71]:
entries_and_exits.diff()

ENTRIES  EXITS
0      NaN    NaN
1     23.0    8.0
2     18.0   18.0
3     71.0   54.0
4    170.0   44.0
5    214.0   42.0
6     87.0   11.0
7     10.0    3.0
8     36.0   89.0
9    153.0  333.0

##  DataFrame applymap()

Similar to Series apply().

It affects whole DataFrame.

In [72]:
entries_and_exits = pd.DataFrame({
    'ENTRIES': [3144312, 3144335, 3144353, 3144424, 3144594,
                 3144808, 3144895, 3144905, 3144941, 3145094],
    'EXITS': [1088151, 1088159, 1088177, 1088231, 1088275,
               1088317, 1088328, 1088331, 1088420, 1088753]
})
entries_and_exits

ENTRIES    EXITS
0  3144312  1088151
1  3144335  1088159
2  3144353  1088177
3  3144424  1088231
4  3144594  1088275
5  3144808  1088317
6  3144895  1088328
7  3144905  1088331
8  3144941  1088420
9  3145094  1088753

In [73]:
df1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]})
df1

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [75]:
df1.applymap(lambda x: x * 2)

a   b   c
0  2   8  14
1  4  10  16
2  6  12  18

## DataFrame apply() and qcut()

Applies function on each column (Series) of data in the DataFrame.

The application of this function are operations that depend on entire column values.

In [77]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)
grades_df

exam1  exam2
Andre       43     24
Barry       81     63
Chris       78     56
Dan         75     56
Emilio      89     67
Fred        70     51
Greta       91     79
Humbert     65     46
Ivan        98     72
James       87     60

### Convert grades using qcut

In [106]:
# qcut() operates on a list, array, or Series. This is the
# result of running the function on a single column of the
# DataFrame.
pd.qcut(grades_df['exam1'],
        [0, 0.1, 0.2, 0.5, 0.8, 1],
        labels=['F', 'D', 'C', 'B', 'A'])

Andre      F
Barry      B
Chris      C
Dan        C
Emilio     B
Fred       C
Greta      A
Humbert    D
Ivan       A
James      B
Name: exam1, dtype: category
Categories (5, object): [F < D < C < B < A]

In [107]:
# qcut() operates on a list, array, or Series. This is the
# result of running the function on a single column of the
# DataFrame.
pd.qcut(grades_df,
        [0, 0.1, 0.2, 0.5, 0.8, 1],
        labels=['F', 'D', 'C', 'B', 'A'])

ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

In [108]:
# qcut() does not work on DataFrames, but we can use apply()
# to call the function on each column separately

def convert_grades_curve(exam_grades):
        # Pandas has a bult-in function that will perform this calculation
        # This will give the bottom 0% to 10% of students the grade 'F',
        # 10% to 20% the grade 'D', and so on. You can read more about
        # the qcut() function here:
        # http://pandas.pydata.org/pandas-docs/stable/generated/pandas.qcut.html
        return pd.qcut(exam_grades,
                       [0, 0.1, 0.2, 0.5, 0.8, 1],
                       labels=['F', 'D', 'C', 'B', 'A'])
    
grades_df.apply(convert_grades_curve)

exam1 exam2
Andre       F     F
Barry       B     B
Chris       C     C
Dan         C     C
Emilio      B     B
Fred        C     C
Greta       A     A
Humbert     D     D
Ivan        A     A
James       B     B

### Standardize DataFrame

In [111]:
df = pd.DataFrame({
    'a': [4, 5, 3, 1, 2],
    'b': [20, 10, 40, 50, 30],
    'c': [25, 20, 5, 15, 10]
})

df

a   b   c
0  4  20  25
1  5  10  20
2  3  40   5
3  1  50  15
4  2  30  10

In [112]:
def std_series(col):
    return (col - col.mean()) / col.std(ddof = 0)

def standardize(df):
    '''
    Fill in this function to standardize each column of the given
    DataFrame. To standardize a variable, convert each value to the
    number of standard deviations it is above or below the mean.
    '''
    return df.apply(std)

In [113]:
standardize(df)

a         b         c
0  0.632456 -0.632456  1.264911
1  1.264911 -1.264911  0.632456
2  0.000000  0.632456 -1.264911
3 -1.264911  1.264911  0.000000
4 -0.632456  0.000000 -0.632456

### apply() and reducing DataFrame to a Series

In [114]:
df = pd.DataFrame({
    'a': [4, 5, 3, 1, 2],
    'b': [20, 10, 40, 50, 30],
    'c': [25, 20, 5, 15, 10]
})
df

a   b   c
0  4  20  25
1  5  10  20
2  3  40   5
3  1  50  15
4  2  30  10

In [116]:
df.apply(np.max)

a     5
b    50
c    25
dtype: int64

Same as df.max().

In [117]:
df.max()

a     5
b    50
c    25
dtype: int64

### apply() and second largest elements

In [149]:
 def second_largest(df):
    '''
    Fill in this function to return the second-largest value of each 
    column of the input DataFrame.
    '''
    return df.apply(second_largest_in_col)

def second_largest_in_col(column):
    return column.sort_values(ascending=False).iloc[1]
   

In [150]:
second_largest_in_col(df['a'])

4

In [151]:
second_largest(df)

a     4
b    40
c    20
dtype: int64

## Adding A DataFrame To A Series


### Adding a Series to a square DataFrame

In [152]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    0: [10, 20, 30, 40],
    1: [50, 60, 70, 80],
    2: [90, 100, 110, 120],
    3: [130, 140, 150, 160]
})

In [153]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [154]:
df

0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

In [155]:
df + s

0   1    2    3
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164

1 was added to each element of first column. 2 was added to each element of second column. And so on.

### Adding a Series to a one-row DataFrame

In [156]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({0: [10], 1: [20], 2: [30], 3:[40]})

In [157]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [158]:
df

0   1   2   3
0  10  20  30  40

In [159]:
df + s

0   1   2   3
0  11  22  33  44

Again each value from the series was added to a single column from the DataFrame.

1 was added to the first column, 2 was added to the second and so on.

### Adding a Series to a one-column DataFrame

So what will happen if I add Series to a DataFrame with only one column?

In [160]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({0: [10, 20, 30, 40]})

In [161]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [162]:
df

0
0  10
1  20
2  30
3  40

In [163]:
df + s

0   1   2   3
0  11 NaN NaN NaN
1  21 NaN NaN NaN
2  31 NaN NaN NaN
3  41 NaN NaN NaN

The result has four columns - one for each value in the series - and every column except the first one contains NaNs.

The first column have one added to each column as before.

### Adding when DataFrame column names match Series index

In [165]:
s = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
df = pd.DataFrame({
    'a': [10, 20, 30, 40],
    'b': [50, 60, 70, 80],
    'c': [90, 100, 110, 120],
    'd': [130, 140, 150, 160]
})

In [166]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [167]:
df

a   b    c    d
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

In [168]:
df + s

a   b    c    d
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164

All previous behaviours were related to the corresponding columns and index names.

### Adding when DataFrame column names don't match Series index.

What happens if index and columns do not match?

In [174]:
s = pd.Series([1, 2, 3, 4], index=["b", "c", "d", "e"])
df = pd.DataFrame({
    'a': [10, 20, 30, 40],
    'b': [50, 60, 70, 80],
    'c': [90, 100, 110, 120],
    'd': [130, 140, 150, 160]
})

In [177]:
s

b    1
c    2
d    3
e    4
dtype: int64

In [178]:
df

a   b    c    d
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

In [179]:
df + s

a     b      c      d   e
0 NaN  51.0   92.0  133.0 NaN
1 NaN  61.0  102.0  143.0 NaN
2 NaN  71.0  112.0  153.0 NaN
3 NaN  81.0  122.0  163.0 NaN

The result is similar to when we added Series and the index did not match.

For each letter that was not present in both the DataFrame and Series the result is NaN.

Other values were matched by letters.

Summary: Adding a DataFrame to a Series, adds each vakue of the Series to one column of the DataFrame.

It matches up the Series to the DataFrane using the index of the Series and the column names of the DataFrame.